### ISSUE TITLE
Dockerfile install fails

### ISSUE THREAD

**Issue by moldcraft** [OpenBazaar/OpenBazaar-Server#101]
Yesterday I installed OpenBazaar-Server on my home PC with some problems https://github.com/OpenBazaar/OpenBazaar-Server/issues/100
Now I tried to install OpenBazaar inside docker on my office PC (to not spam the root OS by installing unnecessary programs)

I did:

```sh
$ git clone https://github.com/OpenBazaar/OpenBazaar-Server.git
$ cd OpenBazaar-Server/
$ sudo docker build .
```

and it failed

![](http://static.md/66434e45ee29c9be68c4143941b3b39f.png)

**Comment by grigio** [comment]
me too
```
seed/httpseed.py:  9: [C:ungrouped-imports] -- Imports from package random are not grouped
seed/httpseed.py: 18: [C:ungrouped-imports] -- Imports from package twisted are not grouped
Warning: option profile is obsolete and it is slated for removal in Pylint 1.6.
Warning: option comment is obsolete and it is slated for removal in Pylint 1.6.
Warning: option required-attributes is obsolete and it is slated for removal in Pylint 1.6.
Warning: option ignore-iface-methods is obsolete and it is slated for removal in Pylint 1.6.
Warning: option zope is obsolete and it is slated for removal in Pylint 1.6.
************* Module seed.peers
seed/peers.py:  3: [I:deprecated-pragma] -- Pragma "disable-all" is deprecated, use "skip-file" instead
seed/peers.py:  3: [I:file-ignored] -- Ignoring entire file
FAIL: Detected 27 files with errors.
make: *** [pycheck] Error 1
INFO[0343] The command [/bin/sh -c make] returned a non-zero code: 2 
```

**Comment by grigio** [comment]
it seems the Dockerfile isn't updated and `pip install -r test_requirements.txt` is missing

**Comment by hoffmabc** [comment]
We don't officially maintain the dockerfile much, so if you want to update it please feel free to do so. It's not in the plan for the core team to fix anything on this at the moment.

**Comment by grigio** [comment]
Ok I'll submit a PR if it fix this bug

**Comment by moldcraft** [comment]
**Thank you** `docker build` works. But `docker run` fails

```
$ sudo docker run <image-id>
...
OpenBazaar Server v0.1 starting...
Generating GUID, this may take a few minutes...
Exception : No UPnP device discovered
2015-12-19 21:48:16+0000 [OpenBazaard] [INFO] Finding NAT Type...
2015-12-19 21:48:33+0000 [OpenBazaard] [INFO] Meet an error, when do Test1 on Changed IP and Port on None:None
2015-12-19 21:48:33+0000 [Server] [INFO] querying seed.openbazaar.org:8080 for peers
2015-12-19 21:48:33+0000 [Server] [INFO] seed.openbazaar.org:8080 returned 13 addresses
Traceback (most recent call last):
  File "openbazaard.py", line 285, in <module>
    Parser(OpenBazaard('/tmp/openbazaard.pid'))
  File "openbazaard.py", line 199, in __init__
    getattr(self, args.command)()
  File "openbazaard.py", line 260, in start
    int(args.restapiport), int(args.websocketport), time.time())
  File "openbazaard.py", line 109, in run
    reactor.listenUDP(port, protocol)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 374, in listenUDP
    p.startListening()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/udp.py", line 175, in startListening
    self._bindSocket()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/udp.py", line 193, in _bindSocket
    skt.bind((self.interface, self.port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: an integer is required
```

**Comment by grigio** [comment]
I think it is a different bug.. the server works for me.
```
docker run -ti -p 18469:18469 --name observer  observer
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
 /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ 
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
        \/|__|        \/     \/       \/      \/      \/     \/     \/

OpenBazaar Server v0.1 starting...
Exception : No UPnP device discovered
2015-12-19 21:20:05+0000 [OpenBazaard] [INFO] Finding NAT Type...
2015-12-19 21:20:05+0000 [OpenBazaard] [INFO] Full Cone on XXX.34.206.83:18467
2015-12-19 21:20:05+0000 [Server] [INFO] querying seed.openbazaar.org:8080 for peers
2015-12-19 21:20:06+0000 [Server] [INFO] seed.openbazaar.org:8080 returned 12 addresses
2015-12-19 21:20:06+0000 [OpenBazaard] [INFO] Startup took 4.57 seconds
2015-12-19 21:20:07+0000 [Server] [INFO] bootstrapping with 12 addresses, finding neighbors...
2015-12-19 21:20:08+0000 [ConnHandler] [INFO] connected to XXX.222.3.208:28467
2015-12-19 21:20:08+0000 [ConnHandler] [INFO] connection with XXX.222.3.208:28467 terminated
2015-12-19 21:20:10+0000 [-] [INFO] Libbitcoin server online
2015-12-19 21:20:27+0000 [OpenBazaard] [INFO] bootstrap complete

```

**Comment by grigio** [comment]
@moldcraft   this is the complete command I run
`docker run -d -p 18469:18469 --name observer -e flags="-a 172.17.42.1" observer`
The hardcoded IP you see is the one you get from `ifconfig docker0` should be the same for you too

**Comment by moldcraft** [comment]
```
$ sudo docker run -p 18469:18469 -e flags="-a 172.17.42.1" --name openbazaar openbazaar
$ sudo docker run -p 18469:18469 -e flags="-a 172.17.0.1" --name openbazaar openbazaar
```

both fails with the same error message

----

```
$ sudo docker --version
Docker version 1.9.1, build a34a1d5
```

**Comment by grigio** [comment]
it seems that in your situation you have to specify in flags the REST and the websocket ports https://github.com/OpenBazaar/OpenBazaar-Server/blob/master/openbazaard.py#L203 because [here](https://github.com/OpenBazaar/OpenBazaar-Server/blob/master/openbazaard.py#L109) an integer is required but it is undefined in your case

**Comment by cpacia** [comment]
Yeah you're trying to use 18469 for the network port (which is 18467 by default) and 18469 is the rest api port. 

You either need to change the rest api port or just leave the ports at the defaults.

**Comment by moldcraft** [comment]
Tried different ports and flags, same error.

**Comment by moldcraft** [comment]
I change the SSD on my laptop, installed the OS (Ubuntu 14.04.3), [installed `docker-engine`](https://docs.docker.com/engine/installation/ubuntulinux), built the docker image and tried to run but [same error](https://github.com/OpenBazaar/OpenBazaar-Server/issues/101#issuecomment-166029720)

**Comment by moldcraft** [comment]
Tried on another (home) PC, and it **started successfully**.

So I think the problem is in network detecting mechanism. At home I have

```
Internet <-> WiFi Router <-> PC
```

at office I have

```
Internet <-> Fiber Router <-> Wifi Router <-> PC
```
