### ISSUE TITLE
Installation issue on Mac OS X

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#108]
I am installing the latest version of OpenBazaar-Server on Max OS X (10.11.1) using `pip install -r requirements.txt`. I have made sure that `libffi` is installed with `brew install libffi`. Nonetheless, I get the following error:

```
Collecting pynacl==0.3.0 (from -r requirements.txt (line 7))
  Downloading PyNaCl-0.3.0.tar.gz (2.6MB)
    100% |████████████████████████████████| 2.6MB 208kB/s
    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:13:10: fatal error: 'ffi.h' file not found
    #include <ffi.h>
             ^
    1 error generated.
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-ZZMQWr/pynacl/setup.py", line 278, in <module>
        "Programming Language :: Python :: 3.4",
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 263, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 568, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 806, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 818, in obtain
        return installer(requirement)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 313, in fetch_build_egg
        return cmd.easy_install(req)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 609, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 639, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 825, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1031, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1019, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'cc' failed with exit status 1
```

**Comment by z3ntu** [comment]
Has brew a package called libffi-dev or libffi-devel ?

**Comment by JustinDrake** [comment]
Any ideas for this @cpacia? It's preventing me from testing on one of my Macs.

**Comment by cpacia** [comment]
No. Other than on linux it's libffi-dev not libffi. I don't know about mac. I'd ask @hoffmabc

**Comment by hoffmabc** [comment]
@justindrake did you try

xcode-select --install

**Comment by JustinDrake** [comment]
Progress! I'm now getting a new issue:

```
Justins-iMac:OpenBazaar-Server justin$ sudo pip install -r requirements.txt
The directory '/Users/justin/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/justin/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): protobuf==2.6.1 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Twisted==14.0.2 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): txrudp==0.5.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pystun==0.1.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 4))
Collecting bitcoin==1.1.36 (from -r requirements.txt (line 5))
  Downloading bitcoin-1.1.36.tar.gz
Collecting gnupg==2.0.2 (from -r requirements.txt (line 6))
  Downloading gnupg-2.0.2.tar.gz (97kB)
    100% |████████████████████████████████| 98kB 2.6MB/s
Collecting pynacl==0.3.0 (from -r requirements.txt (line 7))
  Downloading PyNaCl-0.3.0.tar.gz (2.6MB)
    100% |████████████████████████████████| 2.6MB 217kB/s
Collecting txrestapi==0.2 (from -r requirements.txt (line 8))
  Downloading txrestapi-0.2.tar.gz
Collecting autobahn==0.10.9 (from -r requirements.txt (line 9))
  Downloading autobahn-0.10.9.tar.gz (158kB)
    100% |████████████████████████████████| 159kB 2.2MB/s
Collecting txaio==1.1.0 (from -r requirements.txt (line 10))
  Downloading txaio-1.1.0.tar.gz
Collecting python-libbitcoinclient==0.3.2 (from -r requirements.txt (line 11))
  Downloading python-libbitcoinclient-0.3.2.tar.gz (41kB)
    100% |████████████████████████████████| 45kB 5.3MB/s
Collecting requests==2.7.0 (from -r requirements.txt (line 12))
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
    100% |████████████████████████████████| 471kB 1.1MB/s
Collecting pyopenssl==0.15.1 (from -r requirements.txt (line 13))
  Downloading pyOpenSSL-0.15.1-py2.py3-none-any.whl (102kB)
    100% |████████████████████████████████| 106kB 3.5MB/s
Collecting miniupnpc==1.9 (from -r requirements.txt (line 14))
  Downloading miniupnpc-1.9.tar.gz (71kB)
    100% |████████████████████████████████| 73kB 3.3MB/s
Collecting service-identity (from -r requirements.txt (line 15))
  Downloading service_identity-14.0.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf==2.6.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): zope.interface>=3.6.0 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from Twisted==14.0.2->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): enum34 in /Library/Python/2.7/site-packages (from txrudp==0.5.0->-r requirements.txt (line 3))
Collecting psutil>=1.2.1 (from gnupg==2.0.2->-r requirements.txt (line 6))
  Downloading psutil-3.3.0.tar.gz (261kB)
    100% |████████████████████████████████| 262kB 1.7MB/s
Collecting cffi>=0.8 (from pynacl==0.3.0->-r requirements.txt (line 7))
  Downloading cffi-1.4.2-cp27-none-macosx_10_6_intel.whl (207kB)
    100% |████████████████████████████████| 208kB 1.9MB/s
Requirement already satisfied (use --upgrade to upgrade): six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pynacl==0.3.0->-r requirements.txt (line 7))
Collecting ecdsa (from python-libbitcoinclient==0.3.2->-r requirements.txt (line 11))
  Downloading ecdsa-0.13-py2.py3-none-any.whl (86kB)
    100% |████████████████████████████████| 90kB 3.7MB/s
Collecting pyzmq (from python-libbitcoinclient==0.3.2->-r requirements.txt (line 11))
  Downloading pyzmq-15.2.0-cp27-none-macosx_10_6_intel.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 423kB/s
Collecting cryptography>=0.7 (from pyopenssl==0.15.1->-r requirements.txt (line 13))
  Downloading cryptography-1.2.1-cp27-none-macosx_10_6_intel.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 374kB/s
Collecting characteristic>=14.0.0 (from service-identity->-r requirements.txt (line 15))
  Downloading characteristic-14.3.0-py2.py3-none-any.whl
Collecting pyasn1-modules (from service-identity->-r requirements.txt (line 15))
  Downloading pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting pyasn1 (from service-identity->-r requirements.txt (line 15))
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Collecting pycparser (from cffi>=0.8->pynacl==0.3.0->-r requirements.txt (line 7))
  Downloading pycparser-2.14.tar.gz (223kB)
    100% |████████████████████████████████| 225kB 2.0MB/s
Collecting ipaddress (from cryptography>=0.7->pyopenssl==0.15.1->-r requirements.txt (line 13))
  Downloading ipaddress-1.0.16-py27-none-any.whl
Collecting idna>=2.0 (from cryptography>=0.7->pyopenssl==0.15.1->-r requirements.txt (line 13))
  Downloading idna-2.0-py2.py3-none-any.whl (61kB)
    100% |████████████████████████████████| 61kB 3.1MB/s
Installing collected packages: bitcoin, psutil, gnupg, pycparser, cffi, pynacl, txrestapi, txaio, autobahn, ecdsa, pyzmq, python-libbitcoinclient, requests, ipaddress, pyasn1, idna, cryptography, pyopenssl, miniupnpc, characteristic, pyasn1-modules, service-identity
  Running setup.py install for bitcoin
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-glosH3/bitcoin/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-UpTFYt-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/bitcoin
    copying bitcoin/__init__.py -> build/lib/bitcoin
    copying bitcoin/bci.py -> build/lib/bitcoin
    copying bitcoin/blocks.py -> build/lib/bitcoin
    copying bitcoin/composite.py -> build/lib/bitcoin
    copying bitcoin/deterministic.py -> build/lib/bitcoin
    copying bitcoin/main.py -> build/lib/bitcoin
    copying bitcoin/py2specials.py -> build/lib/bitcoin
    copying bitcoin/py3specials.py -> build/lib/bitcoin
    copying bitcoin/ripemd.py -> build/lib/bitcoin
    copying bitcoin/stealth.py -> build/lib/bitcoin
    copying bitcoin/transaction.py -> build/lib/bitcoin
    running egg_info
    writing bitcoin.egg-info/PKG-INFO
    writing top-level names to bitcoin.egg-info/top_level.txt
    writing dependency_links to bitcoin.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'bitcoin.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'bitcoin.egg-info/SOURCES.txt'
    running build_scripts
    creating build/scripts-2.7
    copying and adjusting pybtctool -> build/scripts-2.7
    changing mode of build/scripts-2.7/pybtctool from 644 to 755
    running install_lib
    copying build/lib/bitcoin/__init__.py -> /Library/Python/2.7/site-packages/bitcoin
    copying build/lib/bitcoin/bci.py -> /Library/Python/2.7/site-packages/bitcoin
    copying build/lib/bitcoin/blocks.py -> /Library/Python/2.7/site-packages/bitcoin
    copying build/lib/bitcoin/composite.py -> /Library/Python/2.7/site-packages/bitcoin
    copying build/lib/bitcoin/deterministic.py -> /Library/Python/2.7/site-packages/bitcoin
    copying build/lib/bitcoin/main.py -> /Library/Python/2.7/site-packages/bitcoin
    copying build/lib/bitcoin/py2specials.py -> /Library/Python/2.7/site-packages/bitcoin
    copying build/lib/bitcoin/py3specials.py -> /Library/Python/2.7/site-packages/bitcoin
    copying build/lib/bitcoin/ripemd.py -> /Library/Python/2.7/site-packages/bitcoin
    copying build/lib/bitcoin/stealth.py -> /Library/Python/2.7/site-packages/bitcoin
    copying build/lib/bitcoin/transaction.py -> /Library/Python/2.7/site-packages/bitcoin
    byte-compiling /Library/Python/2.7/site-packages/bitcoin/__init__.py to __init__.pyc
    byte-compiling /Library/Python/2.7/site-packages/bitcoin/bci.py to bci.pyc
    byte-compiling /Library/Python/2.7/site-packages/bitcoin/blocks.py to blocks.pyc
    byte-compiling /Library/Python/2.7/site-packages/bitcoin/composite.py to composite.pyc
    byte-compiling /Library/Python/2.7/site-packages/bitcoin/deterministic.py to deterministic.pyc
    byte-compiling /Library/Python/2.7/site-packages/bitcoin/main.py to main.pyc
    byte-compiling /Library/Python/2.7/site-packages/bitcoin/py2specials.py to py2specials.pyc
    byte-compiling /Library/Python/2.7/site-packages/bitcoin/py3specials.py to py3specials.pyc
    byte-compiling /Library/Python/2.7/site-packages/bitcoin/ripemd.py to ripemd.pyc
    byte-compiling /Library/Python/2.7/site-packages/bitcoin/stealth.py to stealth.pyc
    byte-compiling /Library/Python/2.7/site-packages/bitcoin/transaction.py to transaction.pyc
    running install_data
    copying LICENSE -> /System/Library/Frameworks/Python.framework/Versions/2.7/
    error: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/LICENSE'

    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-glosH3/bitcoin/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-UpTFYt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-glosH3/bitcoin
```

**Comment by hoffmabc** [comment]
Seems like a permissions problem. Does it work if you sudo?

**Comment by JustinDrake** [comment]
@hoffmabc: It is a sudo. Check the first line of the copy-paste:

`Justins-iMac:OpenBazaar-Server justin$ sudo pip install -r requirements.txt`

**Comment by hoffmabc** [comment]
Can you try doing this in a virtualenv?

```
virtualenv env
source env/bin/activate
pip install -r requirements.txt
```

**Comment by JustinDrake** [comment]
Yes! Cheers Brian.
