### ISSUE TITLE
On refresh profile API hangs

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Server#110]
When viewing a user's page that is not your own, if the refresh button is clicked the call to profile never returns data, freezing the client unless a timeout is set on the AJAX call (which results in an error message).

Two unhandled errors are visible in the command window:

2016-01-04 13:43:33-0500 [OpenBazaarProtocol (UDP)] Unhandled error in Deferred:
Unhandled error in Deferred:
2016-01-04 13:43:33-0500 [OpenBazaarProtocol (UDP)] Unhandled Error
        Traceback (most recent call last):
          File "C:\python27\lib\site-packages\twisted\internet\defer.py", line 490, in _startRunCallbacks
            self._runCallbacks()
          File "C:\python27\lib\site-packages\twisted\internet\defer.py", line 577, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "C:\Users\J\ob\OpenBazaar-Server\api\restapi.py", line 83, in get_node
            _showImage()
          File "C:\python27\lib\site-packages\twisted\internet\defer.py", line 1237, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "C:\python27\lib\site-packages\twisted\internet\defer.py", line 1099, in _inlineCallbacks
            result = g.send(result)
          File "C:\Users\J\ob\OpenBazaar-Server\api\restapi.py", line 71, in _showImage
            request.finish()
          File "C:\python27\lib\site-packages\twisted\web\server.py", line 228, in finish
            return http.Request.finish(self)
          File "C:\python27\lib\site-packages\twisted\web\http.py", line 930, in finish
            "Request.finish called on a request after its connection was lost; "
        exceptions.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

Unhandled Error
Traceback (most recent call last):
  File "C:\python27\lib\site-packages\twisted\internet\defer.py", line 490, in _startRunCallbacks
    self._runCallbacks()
  File "C:\python27\lib\site-packages\twisted\internet\defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\Users\J\ob\OpenBazaar-Server\api\restapi.py", line 83, in get_node
    _showImage()
  File "C:\python27\lib\site-packages\twisted\internet\defer.py", line 1237, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "C:\python27\lib\site-packages\twisted\internet\defer.py", line 1099, in _inlineCallbacks
    result = g.send(result)
  File "C:\Users\J\ob\OpenBazaar-Server\api\restapi.py", line 71, in _showImage
    request.finish()
  File "C:\python27\lib\site-packages\twisted\web\server.py", line 228, in finish
    return http.Request.finish(self)
  File "C:\python27\lib\site-packages\twisted\web\http.py", line 930, in finish
    "Request.finish called on a request after its connection was lost; "
exceptions.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
2016-01-04 13:44:10-0500 [OpenBazaard] [INFO] bootstrap complete
2016-01-04 13:46:42-0500 [ConnHandler] [INFO] connected to 98.223.170.66:28467

**Comment by cpacia** [comment]
Those errors are saying the UI closed the connection before the server was able to return the data.

**Comment by jjeffryes** [comment]
The web dev panel shows the request as still open, and not timed out. Is there something else the client might be doing that would tell the server the connection is closed?

**Comment by drwasho** [comment]
I think this has been fixed @cpacia and @jjeffryes  so I'm going to tentatively close this, given that it's 27 days old. Please reopen if this is still a problem.
