### ISSUE TITLE
Latest comit crashes on OSX

### ISSUE THREAD

**Issue by lunokhod** [OpenBazaar/OpenBazaar-Server#127]
Open-bazaar server was working fine for me about a week ago on OSX, but after pulling the latest commits, I get a fatal error when trying to run it on the testnet:

I am using commit c92c3e14049ec108f6300c9d022678a58f4a6045

~~~~
python openbazaard.py start --testnet
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
 /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ 
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
        \/|__|        \/     \/       \/      \/      \/     \/     \/

OpenBazaar Server v0.1 starting...
2016-01-10 19:19:20+0100 [OpenBazaard] [INFO] Finding NAT Type...
2016-01-10 19:19:20+0100 [OpenBazaard] [INFO] Full Cone on 88.164.182.121:28467
Traceback (most recent call last):
  File "openbazaard.py", line 285, in <module>
    Parser(OpenBazaard('/tmp/openbazaard.pid'))
  File "openbazaard.py", line 198, in __init__
    getattr(self, args.command)()
  File "openbazaard.py", line 260, in start
    int(args.restapiport), int(args.websocketport), time.time())
  File "openbazaard.py", line 86, in run
    node = Node(keys.guid, ip_address, port, signed_pubkey=keys.guid_signed_pubkey, vendor=Profile(db).get().vendor)
  File "/Users/lunokhod/Coin/OpenBazaar-Server/market/profile.py", line 18, in __init__
    self.profile.ParseFromString(self.db.get_proto())
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/message.py", line 186, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 841, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 874, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 636, in DecodeRepeatedField
    raise _DecodeError('Unexpected end-group tag.')
google.protobuf.message.DecodeError: Unexpected end-group tag.
~~~~

**Comment by hoffmabc** [comment]
I think you need to remove your db and start a clean.

**Comment by lunokhod** [comment]
ok. That worked.
