### ISSUE TITLE
osx 10.9.5 _openssl.so

### ISSUE THREAD

**Issue by shayanb** [OpenBazaar/OpenBazaar-Server#132]
I'm on osx 10.9.5, and after installing the requirements in virtualenv, I get this: 
```
$ python openbazaard.py start
Traceback (most recent call last):
  File "openbazaard.py", line 27, in <module>
    from net.sslcontext import ChainedOpenSSLContextFactory
  File "OpenBazaar-Server/net/sslcontext.py", line 2, in <module>
    from OpenSSL import SSL
  File "OpenBazaar-Server/env/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "OpenBazaar-Server/env/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "OpenBazaar-Server/env/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "OpenBazaar-Server/env/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen(OpenBazaar-Server/env/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so, 2): Symbol not found: _BIO_new_CMS
  Referenced from: OpenBazaar-Server/env/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
  Expected in: flat namespace
 in OpenBazaar-Server/env/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
```

**Comment by cpacia** [comment]
try
```
sudo apt-get install libssl-dev
pip install crytography
```

**Comment by cpacia** [comment]
Oh you're on osx. Still try to install the cryptography package. @hoffmabc might know more.

**Comment by shayanb** [comment]
I'm not sure what fixed the issue but I played around with virtualenv and reinstalled the packages over and over again. somehow I managed to get it working outside virtualenv, it still doesnt work if I activate virtualenv that was set up by following the install instruction.

**Comment by hoffmabc** [comment]
Are you sure you were using virtualenv with Python 2?
