### ISSUE TITLE
Unhandled error in Deferred

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#155]
Sometimes I get this error:

```
2016-01-20 11:58:54+0000 [-] Unhandled error in Deferred:
Unhandled error in Deferred:
2016-01-20 11:58:54+0000 [-] Unhandled Error
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1192, in run
        self.mainLoop()
      File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1201, in mainLoop
        self.runUntilCurrent()
      File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 824, in runUntilCurrent
        call.func(*call.args, **call.kw)
      File "/usr/local/lib/python2.7/site-packages/twisted/internet/task.py", line 218, in __call__
        d = defer.maybeDeferred(self.f, *self.a, **self.kw)
    --- <exception caught here> ---
      File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 139, in maybeDeferred
        result = f(*args, **kw)
      File "/usr/local/lib/python2.7/site-packages/obelisk/zmq_fallback.py", line 31, in poll
        while self.poll_once():
      File "/usr/local/lib/python2.7/site-packages/obelisk/zmq_fallback.py", line 40, in poll_once
        self._cb(data, more)
      File "/usr/local/lib/python2.7/site-packages/obelisk/client.py", line 86, in frame_received
        t.reset(10)
      File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 109, in reset
        raise error.AlreadyCalled
    twisted.internet.error.AlreadyCalled: Tried to cancel an already-called event.

Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/task.py", line 218, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 139, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/obelisk/zmq_fallback.py", line 31, in poll
    while self.poll_once():
  File "/usr/local/lib/python2.7/site-packages/obelisk/zmq_fallback.py", line 40, in poll_once
    self._cb(data, more)
  File "/usr/local/lib/python2.7/site-packages/obelisk/client.py", line 86, in frame_received
    t.reset(10)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 109, in reset
    raise error.AlreadyCalled
twisted.internet.error.AlreadyCalled: Tried to cancel an already-called event.
```

**Comment by cpacia** [comment]
what version of python-libbitcoinclient is this?

**Comment by JustinDrake** [comment]
I'm using version [0.3.2](https://github.com/OpenBazaar/OpenBazaar-Server/blob/master/requirements.txt#L10).
