### ISSUE TITLE
'SigningKey' object has no attribute 'to_curve25519_private_key'

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#218]
Fresh install on Mac OS X, database deleted, latest version pulled.

```
OpenBazaar Server v0.1 starting...
Generating GUID, this may take a few minutes...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/justin/Desktop/OpenBazaar-Server/keys/keychain.py", line 49, in create_keychain
    self.encryption_key = self.signing_key.to_curve25519_private_key()
AttributeError: 'SigningKey' object has no attribute 'to_curve25519_private_key'
```

**Comment by cpacia** [comment]
Upgrade to the new version of pynacl.
