### ISSUE TITLE
DATA_FOLDER is commented out in ob.cfg

### ISSUE THREAD

**Issue by tenthirtyone** [OpenBazaar/OpenBazaar-Server#221]
Did a reinstall on my VM and got this error when I fired up OB on testnet

$ python openbazaar.py start --testnet

er(OpenBazaard('/tmp/openbazaard.pid'))
  File "openbazaard.py", line 208, in __init__
    getattr(self, args.command)()
  File "openbazaard.py", line 258, in start
    int(args.heartbeatport), time.time())
  File "openbazaard.py", line 167, in run
    username, password = get_credentials(db)
  File "/home/hayek/OpenBazaar-Server/keys/credentials.py", line 9, in get_credentials
    creds = settings.get_credentials()
  File "/home/hayek/OpenBazaar-Server/db/datastore.py", line 811, in get_credentials
    cursor.execute('''SELECT username, password FROM settings WHERE id=2''')
sqlite3.OperationalError: no such column: username

I omitted the banner for brevity. I found the fix - DATA_FOLDER is commented out in ob.cfg in the latest version of develop.

Pull Request:
https://github.com/drwasho/OpenBazaar-Server/pull/1

**Comment by tcharding** [comment]
You may very well be correct, but I don't believe that you need DATA_FOLDER uncommented unless you have set it to be in a custom location previously. The default behaviour should be handled for you without this variable present in the config file (i.e commented out). Please say if this is not correct for your situation so it can be remedied.

**Comment by tenthirtyone** [comment]
I've been looking into this one since posting the issue. 

I started over. Cloned the repo. Installed all the reqs and tests pass

```
Name           Stmts   Miss  Cover   Missing
--------------------------------------------
db                 1      0   100%   
db.datastore     590     94    84%   28, 98, 102-108, 117, 316-317, 333-337, 461-462, 483-484, 509-510, 544-545, 584, 598, 603-609, 627-628, 667, 686, 695-696, 700-708, 711-713, 716-719, 722-728, 731-733, 740-741, 744-748, 751-763, 766-777, 804-807, 810-812, 827-830, 840, 846, 872
dht                2      0   100%   
dht.crawling     126      6    95%   62-63, 128-129, 153-154
dht.node          88      0   100%   
dht.protocol     183     55    70%   72-78, 92-93, 103, 118-128, 131-139, 166-167, 183-200, 207-208, 227-229
dht.routing      123     18    85%   71-72, 75, 78, 104-106, 109-111, 132-134, 168-172, 189
dht.storage      219     17    92%   125-126, 137-138, 153, 192-193, 206-207, 221-222, 230-231, 234-236, 252
dht.utils         31      0   100%   
market             2      0   100%   
--------------------------------------------
TOTAL           1365    190    86%   
----------------------------------------------------------------------
Ran 92 tests in 4.222s

```

Tests look good.

python openbazaar start --testnet

```
$ python openbazaard.py start --testnet
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
 /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ 
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
        \/|__|        \/     \/       \/      \/      \/     \/     \/

OpenBazaar Server v0.1 starting...
Traceback (most recent call last):
  File "openbazaard.py", line 286, in <module>
    Parser(OpenBazaard('/tmp/openbazaard.pid'))
  File "openbazaard.py", line 208, in __init__
    getattr(self, args.command)()
  File "openbazaard.py", line 258, in start
    int(args.heartbeatport), time.time())
  File "openbazaard.py", line 167, in run
    username, password = get_credentials(db)
  File "/home/hayek/OpenBazaar-Server/keys/credentials.py", line 9, in get_credentials
    creds = settings.get_credentials()
  File "/home/hayek/OpenBazaar-Server/db/datastore.py", line 811, in get_credentials
    cursor.execute('''SELECT username, password FROM settings WHERE id=2''')
sqlite3.OperationalError: no such column: username

```

But I can't find the db file to add the column. If I uncomment the DATA_FOLDER and specify the current working directory it runs:

```
$ python openbazaard.py start --testnet
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
 /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ 
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
        \/|__|        \/     \/       \/      \/      \/     \/     \/

OpenBazaar Server v0.1 starting...
Generating GUID, this may take a few minutes...
Exception : No UPnP device discovered
2016-02-14 22:36:06-0800 [OpenBazaard] [INFO] Finding NAT Type...
2016-02-14 22:36:14-0800 [OpenBazaard] [INFO] Restric NAT on 24.23.118.198:63656
2016-02-14 22:36:14-0800 [Server] [INFO] querying seed.openbazaar.org:8080 for peers
2016-02-14 22:36:15-0800 [Server] [INFO] seed.openbazaar.org:8080 returned 21 addresses
2016-02-14 22:36:15-0800 [OpenBazaard] [INFO] Startup took 16.06 seconds
2016-02-14 22:36:19-0800 [-] [INFO] Libbitcoin server online
2016-02-14 22:36:19-0800 [Server] [INFO] bootstrapping with 21 addresses, finding neighbors...
2016-02-14 22:36:19-0800 [ConnHandler] [INFO] connected to 168.235.89.195:38467
2016-02-14 22:36:19-0800 [ConnHandler] [INFO] connected to 172.73.188.213:28467
2016-02-14 22:36:19-0800 [ConnHandler] [INFO] connected to 104.131.6.245:28467
2016-02-14 22:36:19-0800 [ConnHandler] [INFO] connected to 5.196.227.146:28467
2016-02-14 22:36:19-0800 [ConnHandler] [INFO] connected to 86.31.139.202:28467
2016-02-14 22:36:19-0800 [ConnHandler] [INFO] connected to 68.52.199.74:28467
2016-02-14 22:36:19-0800 [ConnHandler] [INFO] connected to 37.139.1.122:28467
2016-02-14 22:36:19-0800 [ConnHandler] [INFO] connected to 192.241.232.152:28467
2016-02-14 22:36:19-0800 [ConnHandler] [INFO] connected to 82.232.34.210:28467
2016-02-14 22:36:19-0800 [ConnHandler] [INFO] connected to 82.1.213.165:28467
2016-02-14 22:36:19-0800 [ConnHandler] [INFO] connected to 114.77.52.137:28467
2016-02-14 22:36:19-0800 [ConnHandler] [INFO] connected to 128.199.127.191:28467
2016-02-14 22:36:19-0800 [ConnHandler] [INFO] connected to 128.199.118.253:28467
2016-02-14 22:36:19-0800 [ConnHandler] [INFO] connected to 101.165.14.128:28467
2016-02-14 22:36:19-0800 [ConnHandler] [INFO] connected to 101.27.236.88:51400
2016-02-14 22:36:24-0800 [OpenBazaard] [INFO] bootstrap complete

```

But the frontend won't connect

**Comment by tcharding** [comment]
That is an odd one, I could be wrong but I do not think it is related to the location of DATA_FOLDER. Perhaps you could post a message in the slack and someone that knows more than me will no doubt be able to help you out.

**Comment by tenthirtyone** [comment]
Okay, looks like this is a conflict in my filesystem structure.

I run OB from OpenBazaar-Server in ~/ On a test machine it created the ~/OpenBazaar folder. I'm not home to check but right now my guess I need to destroy the ~/OpenBazaar folder and re-run the server

**Comment by tyler-smith** [comment]
You should only need to delete ~/OpenBazaar/OB-Testnet.db and then restart. I'm pretty confident your issue is just an old database.

**Comment by tenthirtyone** [comment]
^^ Tyler got it
