### ISSUE TITLE
2nd+ instance of OpenBazaar-Server intermittent stuck

### ISSUE THREAD

**Issue by ac225519** [OpenBazaar/OpenBazaar-Server#224]
Setup:
1 computer with 1 IP
3 user with 3 home dirs
3 *complete* copies of OpenBazaar-Server with all used python-modules and lib in user space.
   Connected with LD_LIBRARY_PATH (managed by a script called 'start-openbazaar-node')
user1: ./start-openbazaar-node start -t --port=28467 --restapiport=18469 --websocketport=18466    --heartbeatport=18470 --pidfile=/tmp/openbazaard.pid
user2:  ./start-openbazaar-node start -t --port=27467 --restapiport=17469 --websocketport=17466    --heartbeatport=17470 --pidfile=/tmp/openbazaard2.pid
user3: ./start-openbazaar-node start -t --port=26467 --restapiport=16469 --websocketport=16466    --heartbeatport=16470 --pidfile=/tmp/openbazaard3.pid
The 1st instance starts normally.
The 2nd and 3rd instance starts until the message: 
[Server] [INFO] seed.openbazaar.org:8080 returned 28 addresses
And is than stuck there.
Stopping and restarting a couple of times finally starts the instance.

**Comment by ac225519** [comment]
A Traceback of a interrupted stuck instance:

^CTraceback (most recent call last):
  File "./openbazaard.py", line 283, in <module>
    Parser(OpenBazaard('/tmp/openbazaard.pid'))
  File "./openbazaard.py", line 208, in __init__
    getattr(self, args.command)()
  File "./openbazaard.py", line 258, in start
    int(args.heartbeatport), time.time())
  File "./openbazaard.py", line 179, in run
    KeyChain(db, start_server, heartbeat_server)
  File "/home/user2/OpenBazaar-Server_2/keys/keychain.py", line 28, in __init__
    callback(self)
  File "./openbazaard.py", line 111, in start_server
    looping_retry(reactor.listenUDP, port, protocol)
  File "/home/user2/OpenBazaar-Server_2/net/utils.py", line 9, in looping_retry
    time.sleep(0.5)
KeyboardInterrupt

**Comment by saltduck** [comment]
Try to append a new line `raise` into net/utils.py like following and look at the traceback.

```python
        try:
            return func(*args)
        except Exception:
            time.sleep(0.5)
            raise
```

**Comment by ac225519** [comment]
THANK YOU saltduck !
Traceback (most recent call last):
  File "./openbazaard.py", line 283, in <module>
    Parser(OpenBazaard('/tmp/openbazaard.pid'))
  File "./openbazaard.py", line 208, in __init__
    getattr(self, args.command)()
  File "./openbazaard.py", line 258, in start
    int(args.heartbeatport), time.time())
  File "./openbazaard.py", line 179, in run
    KeyChain(db, start_server, heartbeat_server)
  File "/home/user2/OpenBazaar-Server_2/keys/keychain.py", line 28, in __init__
    callback(self)
  File "./openbazaard.py", line 111, in start_server
    looping_retry(reactor.listenUDP, port, protocol)
  File "/home/user2/OpenBazaar-Server_2/net/utils.py", line 7, in looping_retry
    return func(*args)
  File "/home/user2/OpenBazaar-Server_2/32/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 374, in listenUDP
    p.startListening()
  File "/home/user2/OpenBazaar-Server_2/32/lib/python2.7/dist-packages/twisted/internet/udp.py", line 175, in startListening
    self._bindSocket()
  File "/home/user2/OpenBazaar-Server_2/32/lib/python2.7/dist-packages/twisted/internet/udp.py", line 195, in _bindSocket
    raise error.CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:1028: [Errno 98] Address already in use.

**Comment by cpacia** [comment]
I don't know how helpful that is. The reason it's in a loop is because STUN starts up on that port then shuts down and sometimes the server starts before STUN fully closes the socket.

**Comment by cpacia** [comment]
I've run a number of instances recently from one box without issue. If this comes up again we can reopen.
