### ISSUE TITLE
Modifying the description or the about of the page in a certain way locks me out and I have to start from scratch. 

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Server#235]
I got this error by editing the settings and changing the description and about. I copied the description to the about section and I think that this caused the problem.

`[37.139.17.144] out: Unhandled Error
[37.139.17.144] out: Traceback (most recent call last):
[37.139.17.144] out:   File "/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
[37.139.17.144] out:     why = self.lineReceived(line)
[37.139.17.144] out:   File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1655, in lineReceived
[37.139.17.144] out:     self.allContentReceived()
[37.139.17.144] out:   File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1730, in allContentReceived
[37.139.17.144] out:     req.requestReceived(command, path, version)
[37.139.17.144] out:   File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 826, in requestReceived
[37.139.17.144] out:     self.process()
[37.139.17.144] out: --- <exception caught here> ---
[37.139.17.144] out:   File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 184, in process
[37.139.17.144] out:     resrc = self.site.getResourceFor(self)
[37.139.17.144] out:   File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 701, in getResourceFor
[37.139.17.144] out:     return resource.getChildForRequest(self.resource, request)
[37.139.17.144] out:   File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 98, in getChildForRequest
[37.139.17.144] out:     resource = resource.getChildWithDefault(pathElement, request)
[37.139.17.144] out:   File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 201, in getChildWithDefault
[37.139.17.144] out:     return self.getChild(path, request)
[37.139.17.144] out:   File "/usr/local/lib/python2.7/dist-packages/txrestapi/resource.py", line 63, in getChild
[37.139.17.144] out:     return maybeResource(callback)(request, **args)
[37.139.17.144] out:   File "/usr/local/lib/python2.7/dist-packages/txrestapi/resource.py", line 19, in inner
[37.139.17.144] out:     result = f(*args, **kwargs)
[37.139.17.144] out:   File "/root/store/api/restapi.py", line 56, in _authenticate
[37.139.17.144] out:     func(self, request)
[37.139.17.144] out:   File "/root/store/api/restapi.py", line 212, in get_profile
[37.139.17.144] out:     parse_profile(p, None if temp_handle == "" else temp_handle)
[37.139.17.144] out:   File "/root/store/api/restapi.py", line 192, in parse_profile
[37.139.17.144] out:     request.write(str(bleach.clean(json.dumps(profile_json, indent=4), tags=ALLOWED_TAGS)))
[37.139.17.144] out: exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 356: ordinal not in range(128)`

**Comment by cpacia** [comment]
I can't replicate this. Maybe someone else can. It would be help to see which field in the profile has the invalid characters.

**Comment by dsmurrell** [comment]
Try this in the about section:

"Ask questions about OpenBazaar. Anything goes!

Manned by two friendly humans.

Languages supported: English, French"

It died again.

**Comment by JustinDrake** [comment]
Maybe the new line characters? What's the maxlengh on the about section?

**Comment by dsmurrell** [comment]
Could be the spaces. That typed in without spaces seems to work.
