### ISSUE TITLE
Chat doesn't handle any non-ascii characters. 

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Server#244]
An example error thrown is: 

```exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\u2665' in position 0: ordinal not in range(128)```

when I try to send ♥

Cannot send love :(

**Comment by hoffmabc** [comment]
```
2016-02-29 11:30:05-0500 [WSProtocol (AuthenticatedWebSocketProtocol),1,127.0.0.1] Unhandled error in Deferred:
2016-02-29 11:30:05-0500 [WSProtocol (AuthenticatedWebSocketProtocol),1,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "api/ws.py", line 278, in dataReceived

	  File "api/ws.py", line 198, in send_message

	  File "site-packages/twisted/internet/defer.py", line 306, in addCallback

	  File "site-packages/twisted/internet/defer.py", line 295, in addCallbacks

	--- <exception caught here> ---
	  File "site-packages/twisted/internet/defer.py", line 577, in _runCallbacks

	  File "api/ws.py", line 197, in send

	  File "market/network.py", line 491, in send_message

	exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
```

**Comment by dsmurrell** [comment]
Thanks, I should have been more specific.
