### ISSUE TITLE
No OpenBazaar from within Public Libraries

### ISSUE THREAD

**Issue by ac225519** [OpenBazaar/OpenBazaar-Server#248]
Brief Description: 
OpenBazaar-Server is not working within Public Libraries.
Attached the (anonymized) result of http://netalyzr.icsi.berkeley.edu/ in case one desire to work on
this problem.

Operating System (OS and version):  All
OpenBazaar version:  ID:51b1e55 downloaded 2016-Mar-01 03:29:14 UTC
Hardware:  Intel

Reproducible (Always): 

Steps to reproduce:
1.  start OpenBazaar-Server
2.  stuck at: 
2016-03-01 16:42:07+1300 [OpenBazaard] [INFO] Finding NAT Type...
2016-03-01 16:43:21+1300 [OpenBazaard] [INFO] Blocked on None:None
^CTraceback (most recent call last):
  File "./openbazaard.py", line 291, in <module>
    Parser(OpenBazaard('/tmp/openbazaard.pid'))
  File "./openbazaard.py", line 209, in __init__
    getattr(self, args.command)()
  File "./openbazaard.py", line 247, in start
    int(args.heartbeatport), time.time())
  File "./openbazaard.py", line 180, in run
    KeyChain(db, start_server, heartbeat_server)
  File "/home/user/OpenBazaar/OpenBazaar-Server/keys/keychain.py", line 28, in __init__
    callback(self)
  File "./openbazaard.py", line 111, in start_server
    looping_retry(reactor.listenUDP, port, protocol)
  File "/home/user/OpenBazaar/OpenBazaar-Server/net/utils.py", line 9, in looping_retry
    time.sleep(0.5)
KeyboardInterrupt

Additional info (links, images, etc go here):
![library_netalyzr_results 2016-03-03](https://cloud.githubusercontent.com/assets/16848241/13443288/5fb8fd94-e065-11e5-8e23-0bbd4e894fbe.png)

**Comment by drwasho** [comment]
What happened when you used a VPN?

**Comment by ac225519** [comment]
I will try a **suggested** VPN next time I'm in the Library.

**Comment by drwasho** [comment]
I suggest ExpressVPN? Works nicely with other p2p software.

**Comment by cpacia** [comment]
Closing because this is the same issue as #251
