### ISSUE TITLE
Can't start server: Finding NAT Type ... IP:Port -> None:None

### ISSUE THREAD

**Issue by moldcraft** [OpenBazaar/OpenBazaar-Server#251]
Brief Description: When I install the server manually or via .deb it won't start.

Tried on another (home) PC, and it **started successfully**.

So I think the problem is in network detecting mechanism. At home I have

```
Internet <-> WiFi Router <-> PC
```

at office I have

```
Internet <-> Fiber Router <-> Wifi Router <-> PC
```

In console I get

```
Exception : No UPnP device discovered
[OpenBazaard] [INFO] Finding NAT Type...
[OpenBazaard] [INFO] Meet an error, when do Test1 on Changed IP and Port on None:None
```

Operating System (OS and version): Ubuntu 14.04 x64
OpenBazaar version: Any version
Hardware: PC

Reproducible: Always

Steps to reproduce:
1. Start the server

Observed Behavior:
It won't start because it can't detect the external ip (I think)

Expected Behavior:
It should start and connect to nodes.

Additional info (links, images, etc go here):

![](https://static.md/dd0d15287f4cd3a776923ad38313939a.png)

**Comment by cpacia** [comment]
can you do:
```bash
$ python
```
```python
>>> import stun
>>> stun.get_ip_info("0.0.0.0", 12345)
```
And tell me what you get on the machine it doesn't work on.

**Comment by moldcraft** [comment]
```
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import stun
>>> stun.get_ip_info("0.0.0.0", 12345)
('Meet an error, when do Test1 on Changed IP and Port', None, None)
>>>
```

**Comment by cpacia** [comment]
So I probably need some other way getting the IP and port in those cases.

**Comment by moldcraft** [comment]
I am available to test anything you'll say.

I can give you remote access to my PC, just let me know `moldcraft[at]email.com`

**Comment by drwasho** [comment]
I've seen this crop up personally and on other nodes.

**Comment by cryptid11** [comment]
same here but on fedora `python -c 'import stun; print stun.get_ip_info("0.0.0.0", 12345)'` result in:

('Blocked', None, None)

what can I do to fix this? I need to open port on router or can I specify other open port in OB server options?

**Comment by drwasho** [comment]
Try `python openbazaard.py start -tp 12345`

**Comment by cryptid11** [comment]
result in: 
`
2016-03-09 19:30:39+0100 [Server] [INFO] seed.openbazaar.org:8080 returned 50 addresses
2016-03-09 19:30:42+0100 [-] Unhandled Error
	Traceback (most recent call last):
	  File "openbazaard.py", line 247, in start
	    int(args.heartbeatport), time.time())
	  File "openbazaard.py", line 182, in run
	    reactor.run()
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1192, in run
	    self.mainLoop()
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rodomonte/Documents/OpenBazaar-Server/market/network.py", line 1095, in update_listings
	    l.ParseFromString(self.db.listings.get_proto())
	  File "/usr/lib/python2.7/site-packages/google/protobuf/message.py", line 185, in ParseFromString
	    self.MergeFromString(serialized)
	  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1089, in MergeFromString
	    length = len(serialized)
	exceptions.TypeError: object of type 'NoneType' has no len()
	
Unhandled Error
Traceback (most recent call last):
  File "openbazaard.py", line 247, in start
    int(args.heartbeatport), time.time())
  File "openbazaard.py", line 182, in run
    reactor.run()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/rodomonte/Documents/OpenBazaar-Server/market/network.py", line 1095, in update_listings
    l.ParseFromString(self.db.listings.get_proto())
  File "/usr/lib/python2.7/site-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1089, in MergeFromString
    length = len(serialized)
exceptions.TypeError: object of type 'NoneType' has no len()
`

Doing without the tp option it stuck at 
`2016-03-09 19:39:57+0100 [Server] [INFO] seed.openbazaar.org:8080 returned 50 addresses`
