### ISSUE TITLE
Consumer asked us to stop producing

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Server#272]
@cpacia not sure if you've seen this one before but it's new to me.

```
2016-03-06 10:27:46-0500 [-] Unhandled error in Deferred:
Unhandled error in Deferred:
2016-03-06 10:27:46-0500 [-] Unhandled Error
	Traceback (most recent call last):
	Failure: exceptions.Exception: Consumer asked us to stop producing

Unhandled Error
Traceback (most recent call last):
Failure: exceptions.Exception: Consumer asked us to stop producing
2016-03-06 10:27:46-0500 [-] Unhandled error in Deferred:
Unhandled error in Deferred:
2016-03-06 10:27:46-0500 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/brianhoffman/Projects/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/Users/brianhoffman/Projects/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	  File "/Users/brianhoffman/Projects/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/Users/brianhoffman/Projects/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1237, in unwindGenerator
	    return _inlineCallbacks(None, gen, Deferred())
	--- <exception caught here> ---
	  File "/Users/brianhoffman/Projects/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
	    result = g.send(result)
	  File "/Users/brianhoffman/Projects/OpenBazaar-Installer/OpenBazaar-Server/api/restapi.py", line 125, in _showImage
	    request.finish()
	  File "/Users/brianhoffman/Projects/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/web/server.py", line 228, in finish
	    return http.Request.finish(self)
	  File "/Users/brianhoffman/Projects/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/web/http.py", line 930, in finish
	    "Request.finish called on a request after its connection was lost; "
	exceptions.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

Unhandled Error
Traceback (most recent call last):
  File "/Users/brianhoffman/Projects/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 382, in callback
    self._startRunCallbacks(result)
  File "/Users/brianhoffman/Projects/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
    self._runCallbacks()
  File "/Users/brianhoffman/Projects/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/brianhoffman/Projects/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1237, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/Users/brianhoffman/Projects/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
    result = g.send(result)
  File "/Users/brianhoffman/Projects/OpenBazaar-Installer/OpenBazaar-Server/api/restapi.py", line 125, in _showImage
    request.finish()
  File "/Users/brianhoffman/Projects/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/web/server.py", line 228, in finish
    return http.Request.finish(self)
  File "/Users/brianhoffman/Projects/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/web/http.py", line 930, in finish
    "Request.finish called on a request after its connection was lost; "
exceptions.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
2016-03-06 10:27:46-0500 [-] Unhandled error in Deferred:
Unhandled error in Deferred:
2016-03-06 10:27:46-0500 [-] Unhandled Error
	Traceback (most recent call last):
	Failure: exceptions.Exception: Consumer asked us to stop producing

Unhandled Error
Traceback (most recent call last):
Failure: exceptions.Exception: Consumer asked us to stop producing
2016-03-06 10:27:46-0500 [-] Unhandled error in Deferred:
Unhandled error in Deferred:
2016-03-06 10:27:46-0500 [-] Unhandled Error
	Traceback (most recent call last):
	Failure: exceptions.Exception: Consumer asked us to stop producing

Unhandled Error
Traceback (most recent call last):
Failure: exceptions.Exception: Consumer asked us to stop producing
2016-03-06 10:27:46-0500 [-] Unhandled error in Deferred:
Unhandled error in Deferred:
2016-03-06 10:27:46-0500 [-] Unhandled Error
	Traceback (most recent call last):
	Failure: exceptions.Exception: Consumer asked us to stop producing

Unhandled Error
Traceback (most recent call last):
Failure: exceptions.Exception: Consumer asked us to stop producing
2016-03-06 10:27:46-0500 [ConnHandler] [INFO] connection with 115.187.235.141:39676 terminated
2016-03-06 10:27:46-0500 [-] Unhandled error in Deferred:
Unhandled error in Deferred:
2016-03-06 10:27:46-0500 [-] Unhandled Error
	Traceback (most recent call last):
	Failure: exceptions.Exception: Consumer asked us to stop producing

Unhandled Error
Traceback (most recent call last):
```

**Comment by saltduck** [comment]
That's a twisted's issue

**Comment by drwasho** [comment]
Should probably close this @hoffmabc ?

**Comment by tyggrr** [comment]
I can confirm this one:
````
2016-04-09 18:47:09-0400 [-] Unhandled Error
        Traceback (most recent call last):
        Failure: exceptions.Exception: Consumer asked us to stop producing

2016-04-09 18:47:09-0400 [-] Unhandled error in Deferred:
2016-04-09 18:47:09-0400 [-] Unhandled Error
        Traceback (most recent call last):
        Failure: exceptions.Exception: Consumer asked us to stop producing

2016-04-09 18:47:09-0400 [-] Unhandled error in Deferred:
2016-04-09 18:47:09-0400 [-] Unhandled Error
        Traceback (most recent call last):
        Failure: exceptions.Exception: Consumer asked us to stop producing

2016-04-09 18:47:09-0400 [ConnHandler] [INFO] connection with 112.200.242.126:1024 terminated
2016-04-09 18:47:09-0400 [-] Unhandled error in Deferred:
2016-04-09 18:47:09-0400 [-] Unhandled Error
        Traceback (most recent call last):
        Failure: exceptions.Exception: Consumer asked us to stop producing
```
Debian 8.3, OpenBazaar-Server 1.1.2 from git sources

**Comment by hoffmabc** [comment]
No because I'm not sure the cause and we don't have a fix yet.

**Comment by cpacia** [comment]
It doesn't affect anything. Just happens when the UI stops listening for a response from the api server.

**Comment by hoffmabc** [comment]
Ok so closed.
