### ISSUE TITLE
Payment Status Does Not Update After Payment

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/OpenBazaar-Server#301]
Brief Description: after paying for a purchase, the status of the purchase still shows as pending, and does not update even though the seller sees the same purchase as paid for.

See client issue: https://github.com/OpenBazaar/OpenBazaar-Client/issues/1019

**Comment by cpacia** [comment]
This can only happen if the libbitcoin server doesn't return for either one.

**Comment by DivineOmega** [comment]
I'm also experiencing this issue. I've made a payment to a merchant, and although the payment is showing with >6 confirmation on the blockchain, Open Bazaar is reporting 'Payment pending'. 

I believe this also prevents the merchant from seeing my shipping address, as they had to contact me via chat to retrieve it. The shipping tab shows entirely blank.

**Comment by mitzip** [comment]
This may or may not be related, though, the result is the same for me. However, I get an error...
`Unhandled error in Deferred:
2016-04-12 05:57:26+0000 [-] Unhandled error in Deferred:


Traceback (most recent call last):
  File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/openbazaar/.local/lib/python2.7/site-packages/obelisk/zmq_fallback.py", line 36, in poll
    while self.poll_once():
  File "/home/openbazaar/.local/lib/python2.7/site-packages/obelisk/zmq_fallback.py", line 45, in poll_once
    self._cb(data, more)
  File "/home/openbazaar/.local/lib/python2.7/site-packages/obelisk/zmqbase.py", line 126, in frame_received
    self.on_raw_message(id, command, data)
  File "/home/openbazaar/.local/lib/python2.7/site-packages/obelisk/zmqbase.py", line 54, in on_raw_message
    self.trigger_callbacks(id, *res)
  File "/home/openbazaar/.local/lib/python2.7/site-packages/obelisk/zmqbase.py", line 89, in trigger_callbacks
    self._subscriptions[tx_id](*args)
  File "/home/openbazaar/OpenBazaar-Server/market/contracts.py", line 1400, in history_fetched
    c.payment_received()
  File "/home/openbazaar/OpenBazaar-Server/market/contracts.py", line 870, in payment_received
    if self.db.purchase.get_status(order_id) == 0:
exceptions.AttributeError: 'Database' object has no attribute 'purchase'
2016-04-12 05:57:26+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
            self.mainLoop()
          File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
            self.runUntilCurrent()
          File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
            call.func(*call.args, **call.kw)
          File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/task.py", line 239, in __call__
            d = defer.maybeDeferred(self.f, *self.a, **self.kw)
        --- <exception caught here> ---
          File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/home/openbazaar/.local/lib/python2.7/site-packages/obelisk/zmq_fallback.py", line 36, in poll
            while self.poll_once():
          File "/home/openbazaar/.local/lib/python2.7/site-packages/obelisk/zmq_fallback.py", line 45, in poll_once
            self._cb(data, more)
          File "/home/openbazaar/.local/lib/python2.7/site-packages/obelisk/zmqbase.py", line 126, in frame_received
            self.on_raw_message(id, command, data)
          File "/home/openbazaar/.local/lib/python2.7/site-packages/obelisk/zmqbase.py", line 54, in on_raw_message
            self.trigger_callbacks(id, *res)
          File "/home/openbazaar/.local/lib/python2.7/site-packages/obelisk/zmqbase.py", line 89, in trigger_callbacks
            self._subscriptions[tx_id](*args)
          File "/home/openbazaar/OpenBazaar-Server/market/contracts.py", line 1400, in history_fetched
            c.payment_received()
          File "/home/openbazaar/OpenBazaar-Server/market/contracts.py", line 870, in payment_received
            if self.db.purchase.get_status(order_id) == 0:
        exceptions.AttributeError: 'Database' object has no attribute 'purchase'`

**Comment by mitzip** [comment]
I'm also getting this error that seems related...
016-04-12 06:16:56+0000 [-] [ERROR] Libbitcoin server timed out. Refreshing socket and resending requests.
Unhandled Error
Traceback (most recent call last):
  File "openbazaard.py", line 266, in start
    int(args.heartbeatport), time.time())
  File "openbazaard.py", line 198, in run
    reactor.run()
  File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/openbazaar/.local/lib/python2.7/site-packages/obelisk/client.py", line 103, in _reconnect
    return ClientBase._reconnect(self)
  File "/home/openbazaar/.local/lib/python2.7/site-packages/obelisk/zmqbase.py", line 95, in _reconnect
    self._socket.close()
  File "/home/openbazaar/.local/lib/python2.7/site-packages/obelisk/zmq_fallback.py", line 54, in close
    self.loop.stop()
  File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/task.py", line 202, in stop
    assert self.running, ("Tried to stop a LoopingCall that was "
exceptions.AssertionError: Tried to stop a LoopingCall that was not running.

2016-04-12 06:16:56+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "openbazaard.py", line 266, in start
            int(args.heartbeatport), time.time())
          File "openbazaard.py", line 198, in run
            reactor.run()
          File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
            self.mainLoop()
          File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
            self.runUntilCurrent()
        --- <exception caught here> ---
          File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
            call.func(*call.args, **call.kw)
          File "/home/openbazaar/.local/lib/python2.7/site-packages/obelisk/client.py", line 103, in _reconnect
            return ClientBase._reconnect(self)
          File "/home/openbazaar/.local/lib/python2.7/site-packages/obelisk/zmqbase.py", line 95, in _reconnect
            self._socket.close()
          File "/home/openbazaar/.local/lib/python2.7/site-packages/obelisk/zmq_fallback.py", line 54, in close
            self.loop.stop()
          File "/home/openbazaar/.local/lib/python2.7/site-packages/twisted/internet/task.py", line 202, in stop
            assert self.running, ("Tried to stop a LoopingCall that was "
        exceptions.AssertionError: Tried to stop a LoopingCall that was not running.

**Comment by mitzip** [comment]
Alright, the two errors above have been attributed to a now fixed issue (https://github.com/OpenBazaar/OpenBazaar-Server/commit/879dfd37d8a34b602c63dface6c6f02e6319c585#commitcomment-17071666) and libbitcoin server availability... I have no more issues here :)

**Comment by drwasho** [comment]
Is this is still an issue @jjeffryes and @cpacia ? Please close if it's not.
