### ISSUE TITLE
Error on connecting client to server

### ISSUE THREAD

**Issue by dsmurrell** [OpenBazaar/OpenBazaar-Server#320]
Did I have to blow away the database with one of these recent updates? It doesn't seem to be in the required structure.

2016-03-31 07:04:10-0400 [HTTPChannel,1,82.1.213.165] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
            why = self.lineReceived(line)
          File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1655, in lineReceived
            self.allContentReceived()
          File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1730, in allContentReceived
            req.requestReceived(command, path, version)
          File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 826, in requestReceived
            self.process()
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 184, in process
            resrc = self.site.getResourceFor(self)
          File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 701, in getResourceFor
            return resource.getChildForRequest(self.resource, request)
          File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 98, in getChildForRequest
            resource = resource.getChildWithDefault(pathElement, request)
          File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 201, in getChildWithDefault
            return self.getChild(path, request)
          File "/usr/local/lib/python2.7/dist-packages/txrestapi/resource.py", line 63, in getChild
            return maybeResource(callback)(request, **args)
          File "/usr/local/lib/python2.7/dist-packages/txrestapi/resource.py", line 19, in inner
            result = f(*args, **kwargs)
          File "/root/server/api/restapi.py", line 56, in _authenticate
            func(self, request)
          File "/root/server/api/restapi.py", line 916, in get_notifications
            notifications = self.db.notifications.get_notifications()
          File "/root/server/db/datastore.py", line 643, in get_notifications
            imageHash, read FROM notifications''')
        sqlite3.OperationalError: no such column: id

**Comment by grigio** [comment]
I've another unhandled error
```
Unhandled error in Deferred:
2016-04-07 09:18:19+0000 [-] Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 859, in _cbDeferred
    self.callback(self.resultList)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/OpenBazaar-Server/api/restapi.py", line 208, in get_node
    request.finish()
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 224, in finish
    return http.Request.finish(self)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 871, in finish
    "Request.finish called on a request after its connection was lost; "
exceptions.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
2016-04-07 09:18:19+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 859, in _cbDeferred
	    self.callback(self.resultList)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 393, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/OpenBazaar-Server/api/restapi.py", line 208, in get_node
	    request.finish()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 224, in finish
	    return http.Request.finish(self)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 871, in finish
	    "Request.finish called on a request after its connection was lost; "
	exceptions.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

```

**Comment by drwasho** [comment]
Version 1.1.3 should have fixed this. Closing.
