### ISSUE TITLE
Error creating docker container using Dockerfile

### ISSUE THREAD

**Issue by camponez** [OpenBazaar/OpenBazaar-Server#325]
Brief Description: 

Operating System (OS and version): Ubuntu 15.10
OpenBazaar version: master HEAD (944570bb8b452c5170)
Hardware: PC

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always

Steps to reproduce:
1. Try to create a docker container: docker build .

Observed Behavior:
...........

Installing collected packages: PyYAML, bandit, coverage, mock, nose, logilab-common, astroid, pylint, sh, python-coveralls
  Found existing installation: coverage 4.0.3
    Uninstalling coverage-4.0.3:
      Successfully uninstalled coverage-4.0.3
  Found existing installation: mock 1.3.0
    Uninstalling mock-1.3.0:
      Successfully uninstalled mock-1.3.0
  Found existing installation: nose 1.3.7
    Uninstalling nose-1.3.7:
      Successfully uninstalled nose-1.3.7
  Rolling back uninstall of nose
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 835, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1030, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 376, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 315, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: '/usr/local/man/man1'

Expected Behavior:
OpenBazaar Server running.

**Comment by Mikadily** [comment]
Fixed it :)
https://github.com/OpenBazaar/OpenBazaar-Server/pull/331

**Comment by grigio** [comment]
@Mikadily not enough, `pylint` seems to be required in another check
```
./scripts/pycheck.sh
ERROR: pylint not installed.
```

**Comment by grigio** [comment]
Removing this line in the Dockerfile fix the issue:
```
RUN make
```
It seems you need to disable the code checks if you want to compile the image :(

**Comment by Mikadily** [comment]
@grigio pylint is in test_requirements.txt
Where are you trying to build it? I once had an error on AWS but it's fine on DO.

**Comment by grigio** [comment]
This is the Dockerfile I use and it works https://github.com/grigio/docker-apps/blob/master/openbazaar-server/Dockerfile

@Mikadily also in the `make` command

**Comment by camponez** [comment]
When I remove the line: 
`RUN pip install mock coverage nose pylint`
and line:
`RUN make`
it worked.

**Comment by lenolib** [comment]
I stumbled upon the same error on a completely unrelated project. The offending pip-package seems to be nose, which throws an error on reinstallation or upgrade.
```
FROM ubuntu:14.04
RUN apt-get update && apt-get install python-pip
RUN pip install --upgrade pip
RUN pip install nose==1.3.6
RUN pip install nose==1.3.7
```
