### ISSUE TITLE
Error running server

### ISSUE THREAD

**Issue by Jzarecta** [OpenBazaar/OpenBazaar-Server#326]
I get the following error when trying to start the OpenBazar-Server
```
Traceback (most recent call last):
  File "openbazaard.py", line 10, in <module>
    from api.ws import WSFactory, AuthenticatedWebSocketProtocol, AuthenticatedWebSocketFactory
  File "/home/jza/Downloads/OpenBazaar-Server/api/ws.py", line 18, in <module>
    from dht.node import Node
  File "/home/jza/Downloads/OpenBazaar-Server/dht/node.py", line 8, in <module>
    from protos import objects
  File "/home/jza/Downloads/OpenBazaar-Server/protos/objects.py", line 17, in <module>
    import countries as countries__pb2
  File "/home/jza/Downloads/OpenBazaar-Server/protos/countries.py", line 23, in <module>
    x0eWESTERN_SAHARA\x10\xf7\x01\x12\n\n\x05YEMEN\x10\xf8\x01\x12\x0b\n\x06ZAMBIA\x10\xf9\x01\x12\r\n\x08ZIMBABWE\x10\xfa\x01\x12\x10\n\x0b\x41\x46GHANISTAN\x10\xfb\x01\x12\x12\n\rALAND_ISLANDS\x10\xfc\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

**Comment by clehner** [comment]
I also get this error. Debian testing amd64

**Comment by clehner** [comment]
The error went away for me after I installed `protobuf==3.0.0b2` and removed my system's python-protobuf (2.6.1-1.3) package.
