### ISSUE TITLE
ZMQError immediately on starting server

### ISSUE THREAD

**Issue by rjcoupe** [OpenBazaar/OpenBazaar-Server#327]
Brief Description: Immediately after running the server, the output below is shown:
````
$ python openbazaard.py start -a 0.0.0.0
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
 /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
        \/|__|        \/     \/       \/      \/      \/     \/     \/

OpenBazaar Server v0.1 starting...
Exception : No UPnP device discovered
2016-04-05 09:47:32+0000 [OpenBazaard] [INFO] Finding NAT Type...
2016-04-05 09:47:32+0000 [OpenBazaard] [INFO] Full Cone on [redacted]:18467
Traceback (most recent call last):
  File "openbazaard.py", line 304, in <module>
    Parser(OpenBazaard('/tmp/openbazaard.pid'))
  File "openbazaard.py", line 228, in __init__
    getattr(self, args.command)()
  File "openbazaard.py", line 266, in start
    int(args.heartbeatport), time.time())
  File "openbazaard.py", line 196, in run
    KeyChain(db, start_server, heartbeat_server)
  File "/home/ubuntu/OpenBazaar-Server/keys/keychain.py", line 28, in __init__
    callback(self)
  File "openbazaard.py", line 143, in start_server
    libbitcoin_client = LibbitcoinClient(LIBBITCOIN_SERVERS, log=Logger(service="LibbitcoinClient"))
  File "/usr/local/lib/python2.7/dist-packages/obelisk/client.py", line 85, in __init__
    self.listen_heartbeat(heartbeat_port)
  File "/usr/local/lib/python2.7/dist-packages/obelisk/client.py", line 123, in listen_heartbeat
    s = ZmqSocket(frame_received, 3, type=zmq.SUB)
  File "/usr/local/lib/python2.7/dist-packages/obelisk/zmq_fallback.py", line 20, in __init__
    self.public_key, self.secret_key = zmq.curve_keypair()
  File "zmq/backend/cython/utils.pyx", line 60, in zmq.backend.cython.utils.curve_keypair (zmq/backend/cython/utils.c:923)
  File "/usr/local/lib/python2.7/dist-packages/zmq/error.py", line 135, in _check_rc
    raise ZMQError(errno)
zmq.error.ZMQError: Operation not supported
```

Operating System (OS and version): Ubuntu Trusty Tahr
OpenBazaar version: Latest (as time of posting)
Hardware: AWS EC2 t2 Micro

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always


Steps to reproduce:
1. Clone Openbazaar-Server repo
2. Install dependencies
3. Set custom username & password
4. Launch server in non-daemon mode.

Observed Behavior:
Immediate and apparently fatal error above.

Expected Behavior:
Server launching normally.

Additional info (links, images, etc go here):

**Comment by rjcoupe** [comment]
This looks similar to #305, but I do not get any further output after the ZMQError, unlike that bug's author.

**Comment by drwasho** [comment]
Seen this before... `libzmq` needs to be installed this way:

- sudo apt-get install autoconf pkg-config libtool
- git clonehttps://github.com/zeromq/libzmq
- cd libzmq
- ./autogen.sh && ./configure && make -j 4
- make check && make install && sudo ldconfig

**Comment by rjcoupe** [comment]
@drwasho I did that; as I recall make install failed (but then succeeded when I ran it with sudo). I'll try recompiling though, just in case.

**Comment by rjcoupe** [comment]
Recompiling libzmq seems to have resolved it! Not sure why it didn't work the first time around, but all seems well now. Thank you!
