### ISSUE TITLE
zmq connect address type error

### ISSUE THREAD

**Issue by donpdonp** [OpenBazaar/OpenBazaar-Server#330]
Ubuntu, github HEAD (944570b) sever startup looks good until

```
2016-04-05 10:41:23-0700 [-] OpenBazaarProtocol starting on 44728
2016-04-05 10:41:23-0700 [-] Starting protocol <net.wireprotocol.OpenBazaarProtocol object at 0x7fb64a024690>
2016-04-05 10:41:23-0700 [-] WSFactory (AuthenticatedWebSocketFactory) starting on 18466
2016-04-05 10:41:23-0700 [-] Starting factory <api.ws.WSFactory instance at 0x7fb64a031e60>
2016-04-05 10:41:23-0700 [-] Starting factory <api.ws.AuthenticatedWebSocketFactory instance at 0x7fb64a031ea8>
2016-04-05 10:41:23-0700 [-] RestAPI starting on 18469
2016-04-05 10:41:23-0700 [-] Starting factory <api.restapi.RestAPI instance at 0x7fb649fdb170>
Traceback (most recent call last):
  File "openbazaard.py", line 304, in <module>
    Parser(OpenBazaard('/tmp/openbazaard.pid'))
  File "openbazaard.py", line 228, in __init__
    getattr(self, args.command)()
  File "openbazaard.py", line 266, in start
    int(args.heartbeatport), time.time())
  File "openbazaard.py", line 196, in run
    KeyChain(db, start_server, heartbeat_server)
  File "/home/donp/code/openbazaar/server/keys/keychain.py", line 28, in __init__
    callback(self)
  File "openbazaard.py", line 143, in start_server
    libbitcoin_client = LibbitcoinClient(LIBBITCOIN_SERVERS, log=Logger(service="LibbitcoinClient"))
  File "/usr/local/lib/python2.7/dist-packages/obelisk/client.py", line 66, in __init__
    ClientBase.__init__(self, address)
  File "/usr/local/lib/python2.7/dist-packages/obelisk/zmqbase.py", line 32, in __init__
    self._socket = self.setup(address)
  File "/usr/local/lib/python2.7/dist-packages/obelisk/zmqbase.py", line 134, in setup
    s.connect(address)
  File "/usr/local/lib/python2.7/dist-packages/obelisk/zmq_fallback.py", line 23, in connect
    self._socket.connect(address)
  File "zmq/backend/cython/socket.pyx", line 466, in zmq.backend.cython.socket.Socket.connect (zmq/backend/cython/socket.c:4234)
TypeError: expected str, got: [('tcp://libbitcoin1.openbazaar.org:9091', 'ptCDh+i&@k3CYEa)(tC=j9$yN/eD&}@LJojDUGo7'), ('tcp://libbitcoin3.openbazaar.org:9091', 'pco)6}^g!]5b7#byrx>[=MCI#W?DCF}K3FoS6nTu')]


```

**Comment by hoffmabc** [comment]
You have an old python-libbitcoinclient it looks like. which version do you have?

```
pip show python-libbitcoinclient
```

**Comment by donpdonp** [comment]
oh yes! 0.3 old, pip install --upgrade fixed it. thanks!
