### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by rfwferreira** [OpenBazaar/OpenBazaar-Server#339]
Brief Description: 

After the `make` part I receive the following error message:

```
openbazaard.py:279: [I:locally-disabled] -- Locally disabling unused-variable (W0612)
PASS: Successfully checked 63 files.
nosetests -vs --with-doctest --with-coverage --cover-package=dht --cover-package=db --cover-package=market --cover-inclusive ./dht/tests ./db/tests ./market/tests
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
Failure: ImportError (No module named google.protobuf.internal) ... ERROR
Failure: ImportError (No module named nacl.signing) ... ERROR
Failure: ImportError (No module named twisted.trial) ... ERROR
Failure: ImportError (No module named nacl.signing) ... ERROR
Failure: ImportError (No module named twisted.trial) ... ERROR
Failure: ImportError (No module named twisted.trial) ... ERROR
Failure: ImportError (No module named twisted.trial) ... ERROR
Failure: ImportError (No module named google.protobuf.internal) ... ERROR
Failure: ImportError (No module named twisted.trial) ... ERROR
Failure: ImportError (No module named twisted.trial) ... ERROR
Failure: ImportError (No module named twisted.trial) ... ERROR
Failure: ImportError (No module named twisted.trial) ... ERROR

======================================================================
ERROR: Failure: ImportError (No module named google.protobuf.internal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/rafael/OpenBazaar-Server/dht/tests/utils.py", line 8, in <module>
    from dht.node import Node
  File "/home/rafael/OpenBazaar-Server/dht/node.py", line 8, in <module>
    from protos import objects
  File "/home/rafael/OpenBazaar-Server/protos/objects.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ImportError: No module named google.protobuf.internal

======================================================================
ERROR: Failure: ImportError (No module named nacl.signing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/rafael/OpenBazaar-Server/dht/tests/test_crawling.py", line 4, in <module>
    import nacl.signing
ImportError: No module named nacl.signing

======================================================================
ERROR: Failure: ImportError (No module named twisted.trial)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/rafael/OpenBazaar-Server/dht/tests/test_node.py", line 4, in <module>
    from twisted.trial import unittest
ImportError: No module named twisted.trial

======================================================================
ERROR: Failure: ImportError (No module named nacl.signing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/rafael/OpenBazaar-Server/dht/tests/test_protocol.py", line 7, in <module>
    import nacl.signing
ImportError: No module named nacl.signing

======================================================================
ERROR: Failure: ImportError (No module named twisted.trial)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/rafael/OpenBazaar-Server/dht/tests/test_routing.py", line 1, in <module>
    from twisted.trial import unittest
ImportError: No module named twisted.trial

======================================================================
ERROR: Failure: ImportError (No module named twisted.trial)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/rafael/OpenBazaar-Server/dht/tests/test_storage.py", line 4, in <module>
    from twisted.trial import unittest
ImportError: No module named twisted.trial

======================================================================
ERROR: Failure: ImportError (No module named twisted.trial)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/rafael/OpenBazaar-Server/dht/tests/test_utils.py", line 3, in <module>
    from twisted.trial import unittest
ImportError: No module named twisted.trial

======================================================================
ERROR: Failure: ImportError (No module named google.protobuf.internal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/rafael/OpenBazaar-Server/db/tests/test_datastore.py", line 4, in <module>
    from db.datastore import Database
  File "/home/rafael/OpenBazaar-Server/db/datastore.py", line 7, in <module>
    from dht.node import Node
  File "/home/rafael/OpenBazaar-Server/dht/node.py", line 8, in <module>
    from protos import objects
  File "/home/rafael/OpenBazaar-Server/protos/objects.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ImportError: No module named google.protobuf.internal

======================================================================
ERROR: Failure: ImportError (No module named twisted.trial)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/rafael/OpenBazaar-Server/market/tests/test_btcprice.py", line 4, in <module>
    from twisted.trial import unittest
ImportError: No module named twisted.trial

======================================================================
ERROR: Failure: ImportError (No module named twisted.trial)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/rafael/OpenBazaar-Server/market/tests/test_listeners.py", line 1, in <module>
    from twisted.trial import unittest
ImportError: No module named twisted.trial

======================================================================
ERROR: Failure: ImportError (No module named twisted.trial)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/rafael/OpenBazaar-Server/market/tests/test_profile.py", line 1, in <module>
    from twisted.trial import unittest
ImportError: No module named twisted.trial

======================================================================
ERROR: Failure: ImportError (No module named twisted.trial)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/rafael/anaconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/rafael/OpenBazaar-Server/market/tests/test_protocol.py", line 1, in <module>
    from twisted.trial import unittest
ImportError: No module named twisted.trial

----------------------------------------------------------------------
Ran 12 tests in 0.050s

FAILED (errors=12)
make: *** [unittest] Error 1
```

Operating System (OS and version): 

`Ubuntu 12.04`

**Comment by grigio** [comment]
It works for me with this https://github.com/grigio/docker-apps/blob/master/openbazaar-server/Dockerfile
