### ISSUE TITLE
OpenBazar Server not connecting to Mac

### ISSUE THREAD

**Issue by horsecoin** [OpenBazaar/OpenBazaar-Server#341]
Brief Description: 

Operating System (OS and version): OS X Yosemite 10.10.5  (for the store client)
Ubuntu 15.10 (GNU/Linux 4.2.0-27-generic x86_64)  (for the server)
OpenBazaar version: I just pulled the latest version 1 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
Always happens when I try to reconnect from the client after inputting my username and password

Steps to reproduce:
1. python2.7 -m pip install -r requirements.txt
2. python openbazaard.py start -d -a [my client ip went here]
3. 

Observed Behavior:
2016-04-07 01:14:25-0700 [MarketProtocol] [INFO] serving store listings to 70.65.156.182:35530
2016-04-07 01:14:25-0700 [MarketProtocol] [INFO] serving store listings to 84.72.86.75:18467
2016-04-07 01:14:50-0700 [MarketProtocol] [INFO] serving store listings to 84.72.86.75:18467
2016-04-07 01:15:11-0700 [MarketProtocol] [INFO] serving user metadata to 70.65.156.182:35530
2016-04-07 01:15:25-0700 [MarketProtocol] [INFO] serving store listings to 70.65.156.182:35530
2016-04-07 01:16:09-0700 [MarketProtocol] [INFO] serving user metadata to 212.33.95.179:18467
2016-04-07 01:16:13-0700 [ConnHandler] [INFO] connected to 90.144.216.195:35073
2016-04-07 01:16:31-0700 [ConnHandler] [INFO] connected to 159.203.250.83:18467
2016-04-07 01:16:43-0700 [ConnHandler] [INFO] connected to 92.222.169.133:18467
2016-04-07 01:16:57-0700 [MarketProtocol] [INFO] serving user metadata to 92.222.169.133:18467

##############then when I try to connect this happens from the client 

Unhandled Error
Traceback (most recent call last):
  File "/home/nick/.local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/nick/.local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/nick/.local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/home/nick/.local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/home/nick/.local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 1074, in doRead
    protocol.makeConnection(transport)
  File "/home/nick/.local/lib/python2.7/site-packages/twisted/protocols/policies.py", line 75, in makeConnection
    self.wrappedProtocol.makeConnection(self)
exceptions.AttributeError: 'NoneType' object has no attribute 'makeConnection'

2016-04-07 01:18:06-0700 [txws.WebSocketFactory] Unhandled Error
        Traceback (most recent call last):
          File "/home/nick/.local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/home/nick/.local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/nick/.local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
          File "/home/nick/.local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
            why = selectable.doRead()
        --- <exception caught here> ---
          File "/home/nick/.local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 1074, in doRead
            protocol.makeConnection(transport)
          File "/home/nick/.local/lib/python2.7/site-packages/twisted/protocols/policies.py", line 75, in makeConnection
            self.wrappedProtocol.makeConnection(self)
        exceptions.AttributeError: 'NoneType' object has no attribute 'makeConnection'

2016-04-07 01:18:22-0700 [ConnHandler] [INFO] connection with 94.42.136.198:37172 terminated
2016-04-07 01:18:22-0700 [ConnHandler] [INFO] connection with 23.254.128.38:18467 terminated

Expected Behavior:
I expect to connect.

Additional info (links, images, etc go here):
followed this tutorial / guide
https://openbazaar.zendesk.com/hc/en-us/articles/207852873-Guide-to-Setting-up-OpenBazaar-Server-on-a-VPS

Thanks in Advance,
Nick T.

**Comment by grigio** [comment]
I had success with this edited Dockerfile https://github.com/grigio/docker-apps/blob/master/openbazaar-server/Dockerfile and it is also easier than the official docs

**Comment by horsecoin** [comment]
Thank you, that is exactly what I was looking for.  I will give it a try.

**Comment by horsecoin** [comment]
The docker file worked for getting all the dependencies, it was a lot simpler than the other route.  Also the twisted errors are gone.  So it seems my container on my UBUNTU  vps is running.
sudo docker run -e flags="-a 76.88.164.193" 2a827e90721f

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
135a9e035cf9        2a827e90721f        "/bin/sh -c 'python o"   11 hours ago        Up 11 hours                             sad_thompson
 
I am new to docker, not sure if my run command above is correct for connecting to home computer.
The -a flag is for the ip of the client running on a different computer correct? The command I was running before docker was:
python openbazaard.py start -d -a 76.88.164.193

The reason being I still cannot connect from my client on my home computer.  Will I need to set up dynamic dns on the home computer? As far as I know my home computer does not have a static ip (even though it does not change much) If anyone knows how to get through the Airport please let me know.

**Comment by grigio** [comment]
@hoffmabc `76.88.164.193` doesn't seem a local ip.. if it could change you should use something like no-ip.org or access to you OB server via a local static ip in your lan (like 192.168.1.x), but it will work only from inside your network.

Any path you choose it should be reachable like this:
```
curl -I http://192.168.1.3:18469                   ⏎
HTTP/1.1 404 Not Found
Date: Sun, 10 Apr 2016 18:38:07 GMT
Content-Length: 167
Content-Type: text/html; charset=utf-8
Server: TwistedWeb/16.1.0
```

**Comment by horsecoin** [comment]
Thanks- closing this issue since I got the OpenBazaar server working and now it is just a networking issue on my side.

**Comment by horsecoin** [comment]
Just an update, I just finally get my Mac client connected to OB running on my separate UBUBTU VPS.
I had to use docker version info below:
○ → docker -- version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:38:59 2016
 OS/Arch:      linux/amd64

○ → sudo docker ps -l
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                                             NAMES
f0f54e8005e9        6904aeb234bd        "/bin/sh -c 'python o"   About a minute ago   Up About a minute   0.0.0.0:18466-18470->18466-18470/tcp, 18469/udp   sharp_golick

##################
cd OpenBazaar-Server
sudo docker build .
############
Heres how I run
############
sudo docker run -i -p 18466-18470:18466-18470/tcp 6904aeb234bd
#############
VERY IMPORTANT:
The actual working docker file I used is at the link below.
https://hub.docker.com/r/hax10r88/openbazaar-server/
The docker file for this master repository did not work for me as of today. Please note the username and password are set (overridden) to default username "user" and password "pass" in this docker file.

FROM ubuntu:14.04

# Examples
# docker build -t observer .
# docker run --rm -it -e flags="--help" observer
# docker run -d --name observer -e flags="--testnet" observer
# docker logs observer

RUN apt-get update
RUN apt-get install -y python-dev python-pip build-essential git libffi-dev libssl-dev
RUN pip install pyopenssl ndg-httpsclient pyasn1
RUN pip install --upgrade pip virtualenv
RUN git clone https://github.com/OpenBazaar/OpenBazaar-Server.git
WORKDIR /OpenBazaar-Server/
RUN pip install -r requirements.txt && pip install -r test_requirements.txt
RUN make
RUN adduser --disabled-password --gecos \"\" openbazaar
RUN chown -R openbazaar:openbazaar /OpenBazaar-Server
RUN mkdir /home/openbazaar/.openbazaar
RUN chown -R openbazaar:openbazaar /home/openbazaar/.openbazaar

USER openbazaar
# customize your OpenBazaar server access
RUN sed -i -- 's/#USERNAME = username/USERNAME = user/g' ob.cfg
RUN sed -i -- 's/#PASSWORD = password/PASSWORD = pass/g' ob.cfg

EXPOSE 18469/udp 18466 18469 18470

CMD python openbazaard.py start -l debug -a 0.0.0.0 $flags
