### ISSUE TITLE
Remote connection issues

### ISSUE THREAD

**Issue by mariodian** [OpenBazaar/OpenBazaar-Server#342]
Brief Description: 

I've set up my OB server on AWS. Everything runs fine, but when I try to connect to the server from my local computer via OB client, I get the following error in a console where the server runs http://pastebin.com/CGHW2jMV

Operating System (OS and version): Ubuntu 14.04
OpenBazaar version: latest from github
Hardware: Amazon AWS free tier

Reproducible: Always

**Comment by horsecoin** [comment]
I have same issue here.  I am trying to figure out if it is a port blocked somewhere.  I just added OpenBazaar to my Mac firewall settings but that did not help yet.  I was hoping to be able to get this set up, but I did not know you had to be a rocket scientist to get it to work!  I am sure it is some very small setting we are missing somewhere.  Could someone map out all the ports that are mandatory to enable for this to work? Right now my OpenBazaar circle loading arrows just keeps spinning on the mac and won't let me in when the server is on.  The server seems to be working but not for my store!

**Comment by hoffmabc** [comment]
I'm having a hard time understanding what's happening in this log. It's almost unreadable! =(

**Comment by mariodian** [comment]
@horsecoin I tried SSL on/off and no luck. It's not the firewall either (nmap says all the necessary ports are open).

**Comment by mariodian** [comment]
```
git pull
Updating 41f83b6..9722851
```

These 2 commits seem to fix it for me. However if the SSL is on, I have to absolutely use it on the client otherwise it won't connect.

**Comment by horsecoin** [comment]
Wow thanks for the input.  I am trying SSL too however I am coming up with this error right now:

OpenBazaar Server v0.1 starting...
Traceback (most recent call last):
  File "openbazaard.py", line 304, in <module>
    Parser(OpenBazaard('/tmp/openbazaard.pid'))
  File "openbazaard.py", line 228, in __init__
    getattr(self, args.command)()
  File "openbazaard.py", line 266, in start
    int(args.heartbeatport), time.time())
  File "openbazaard.py", line 188, in run
    ChainedOpenSSLContextFactory(SSL_KEY, SSL_CERT), interface=interface)
  File "/home/nick/.local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 505, in listenSSL
    port = self.listenTCP(port, tlsFactory, backlog, interface)
  File "/home/nick/.local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 478, in listenTCP
    p.startListening()
  File "/home/nick/.local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 984, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on 0.0.0.0:18470: [Errno 98] Address already in use.

So I am currently checking my ports.  Looking into this will update if there is any solution.

**Comment by horsecoin** [comment]
killed the PID, got rid of that error.  Still testing but no connection yet!
nick@coininstant:~$ sudo netstat -lpn |grep :18470
[sudo] password for nick: 
tcp        0      0 0.0.0.0:18470           0.0.0.0:*               LISTEN      28399/python    
nick@coininstant:~$ kill 28399
