### ISSUE TITLE
OSError: `GLIBC_2.18' not found && libc6 already updated.

### ISSUE THREAD

**Issue by rfwferreira** [OpenBazaar/OpenBazaar-Server#344]
Brief Description: 

Installed openbazaar via .deb version and when i tried to start

```
rafael@rafael-RV415:~$ openbazaar
Starting OpenBazaar Server
[STR] stderr "Traceback (most recent call last):
"
[STR] stderr "  File "<string>", line 11, in <module>
  File "/home/hoffmabc/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "api/restapi.py", line 6, in <module>
  File "/home/hoffmabc/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/obelisk/__init__.py", line 3, in <module>
  File "/home/hoffmabc/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/obelisk/client.py", line 3, in <module>
  File "/home/hoffmabc/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/obelisk/zmqbase.py", line 10, in <module>
  File "/home/hoffmabc/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/obelisk/zmq_fallback.py", line 1, in <module>
  File "/home/hoffmabc/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/zmq/__init__.py", line 49, in <module>
  File "<string>", line 124, in __init__
  File "ctypes/__init__.py", line 365, in __init__
OSError: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/_MEIaBKrje/libstdc++.so.6)
openbazaard returned -1
"
exited with 255
[END] stdout ""
[END] stderr "Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/home/hoffmabc/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "api/restapi.py", line 6, in <module>
  File "/home/hoffmabc/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/obelisk/__init__.py", line 3, in <module>
  File "/home/hoffmabc/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/obelisk/client.py", line 3, in <module>
  File "/home/hoffmabc/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/obelisk/zmqbase.py", line 10, in <module>
  File "/home/hoffmabc/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/obelisk/zmq_fallback.py", line 1, in <module>
  File "/home/hoffmabc/OpenBazaar-Installer/OpenBazaar-Server/env/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/zmq/__init__.py", line 49, in <module>
  File "<string>", line 124, in __init__
  File "ctypes/__init__.py", line 365, in __init__
OSError: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/_MEIaBKrje/libstdc++.so.6)
openbazaard returned -1
"

```

I'm using an Ubuntu 12.04

Operating System (OS and version): 
OpenBazaar version: 
Hardware: 

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Steps to reproduce:
1. 
2. 
3. 

Observed Behavior:

Expected Behavior:

Additional info (links, images, etc go here):

**Comment by todu** [comment]
I seem to have the same problem as this issue creator.

none of the yet released versions work on Ubuntu 12.04. I get the following two error messages that I think are the cause that it doesn't work:

`[STR] stderr "/lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.18 not found (required by /tmp/_MEID5idUI/libstdc++.so.6)"`

and

```
OSError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/_MEIAuL3IH/libstdc++.so.6)
openbazaard returned -1
```

I don't think that Ubuntu 12.04 has the required "GLIBC_2.18" package because I get this result when I run the following command:

```
# dpkg -l|grep -i libc
ii  libc6                                      2.15-0ubuntu10.13                          Embedded GNU C Library: Shared libraries

```
It seems like the current openbazaar .deb package depends on "libc6" to be of at least version 2.18 but that the installed version is only 2.15.

I tried to install the package by running this command:

`# dpkg -i openbazaar_1.1.2_amd64.deb`

And then I ran "openbazaar" on a bash prompt. It ran but with the above error messages on the console and the client software said that it could not connect to the server daemon (openbazaard) because the server daemon never successfully started.

**Comment by hoffmabc** [comment]
Are you trying to run this on a headless server? Do you intend to use the GUI? This is not a server only .deb package.

**Comment by todu** [comment]
I'm trying to run it in a Ubuntu Unity window environment on my local desktop computer.
