### ISSUE TITLE
VerifyScriptError on complete_order

### ISSUE THREAD

**Issue by clehner** [OpenBazaar/OpenBazaar-Server#347]
I have an open order as a buyer where I get an error when I try to complete the order. When I press the Save button in OpenBazaar-Client, nothing happens. Opening the web inspector shows that the request to `api/v1/complete_order` fails with 500 (Internal Server Error).

The stack trace in the server console is as follows:
```
2016-04-08 17:19:59-0400 [HTTPChannel (TLSMemoryBIOProtocol),0,74.89.195.197] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/src/OpenBazaar-Server/env/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1408, in dataReceived
            finishCallback(data[contentLength:])
          File "/usr/local/src/OpenBazaar-Server/env/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1673, in _finishRequestBody
            self.allContentReceived()
          File "/usr/local/src/OpenBazaar-Server/env/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1736, in allContentReceived
            req.requestReceived(command, path, version)
          File "/usr/local/src/OpenBazaar-Server/env/local/lib/python2.7/dist-packages/twisted/web/http.py", line 762, in requestReceived
            self.process()
        --- <exception caught here> ---
          File "/usr/local/src/OpenBazaar-Server/env/local/lib/python2.7/dist-packages/twisted/web/server.py", line 178, in process
            resrc = self.site.getResourceFor(self)
          File "/usr/local/src/OpenBazaar-Server/env/local/lib/python2.7/dist-packages/twisted/web/server.py", line 732, in getResourceFor
            return resource.getChildForRequest(self.resource, request)
          File "/usr/local/src/OpenBazaar-Server/env/local/lib/python2.7/dist-packages/twisted/web/resource.py", line 98, in getChildForRequest
            resource = resource.getChildWithDefault(pathElement, request)
          File "/usr/local/src/OpenBazaar-Server/env/local/lib/python2.7/dist-packages/twisted/web/resource.py", line 201, in getChildWithDefault
            return self.getChild(path, request)
          File "/usr/local/src/OpenBazaar-Server/env/local/lib/python2.7/site-packages/txrestapi/resource.py", line 63, in getChild
            return maybeResource(callback)(request, **args)
          File "/usr/local/src/OpenBazaar-Server/env/local/lib/python2.7/site-packages/txrestapi/resource.py", line 19, in inner
            result = f(*args, **kwargs)
          File "/usr/local/src/OpenBazaar-Server/api/restapi.py", line 58, in _authenticate
            func(self, request)
          File "/usr/local/src/OpenBazaar-Server/api/restapi.py", line 816, in complete_order
            anonymous=str_to_bool(request.args["anonymous"]) if "anonymous" in request.args else True)
          File "/usr/local/src/OpenBazaar-Server/market/contracts.py", line 635, in add_receipt
            tx.multisign(signatures, redeem_script)
          File "/usr/local/src/OpenBazaar-Server/market/transactions.py", line 118, in multisign
            self.tx, i, (SCRIPT_VERIFY_P2SH,))
          File "/usr/local/src/OpenBazaar-Server/env/local/lib/python2.7/site-packages/bitcoin/core/scripteval.py", line 748, in VerifyScript
            raise VerifyScriptError("P2SH inner scriptPubKey returned false")
        bitcoin.core.scripteval.VerifyScriptError: P2SH inner scriptPubKey returned false
```

Client: latest master (OpenBazaar/OpenBazaar-Server@97228515340006a3cd6c866b1ec4484d77b5bc55), node v4.3.1
Server: latest master (OpenBazaar/OpenBazaar-Client@166a3e254ff0449cdc4483125af2a668d366d872), Python 2.7.11+
OS: Debian testing amd64

The error still happens after I restarted my client and server. I have not tried to reproduce the error in any other order. In the affected order, I sent three transactions to the escrow address before the balance was the full amount, because the exchange seemed to change during the course of the order.

It looks like verifying the redeem script is failing. What could be causing this?

**Comment by cpacia** [comment]
Were you testing this with your own nodes?

I've had this issue before but I believed I fixed it. 

If you can send me the contract json for both parties I can rebuild the transaction and try to see what the problem is.

**Comment by enkumber** [comment]
is it safe to post the contracts here?

**Comment by cpacia** [comment]
you can email them to me if you want. I also have a pgp key you can use.

**Comment by enkumber** [comment]
I'm ok with it

**Comment by enkumber** [comment]
Sent!

**Comment by clehner** [comment]
Sent mine as well

**Comment by cpacia** [comment]
@clehner or @enkumber can you guys resend the buyer json. I can only find the seller json in the inbox.

**Comment by cpacia** [comment]
nvm I found it. I'll see what I can do.

**Comment by cpacia** [comment]
I found the issue. The buyer's node never detected the third payment. Likely a result of the libbitcoin server problems we've been having causing downtime. 

Normally the client loops through unfunded (or partially funded in this case) order and checks for payment. So when the libbitcoin comes online, the client will detect the payment. In this case I think what happened was the sending of the order confirmation by the seller (who's client did detect all three payments) caused the buyer's client to stop listening.... which lead to the tx being signed with not enough inputs. 

I told @clehner how to fix it. 

I need to make it not stop checking for funding even after the order confirmation is sent.

**Comment by clehner** [comment]
@cpacia I applied the fix you suggested, to add the missing item to `outpoint`, but I still get the VerifyScriptError when I try to complete the order. Is there something else in the database that I should update or check?

**Comment by cpacia** [comment]
You know what, the order probably matters. I'm not sure what order the seller signed then in. I would maybe try changing the order of those outpoints.

**Comment by cpacia** [comment]
If you can't get it or it's too much work I can just send some coins to that address to payout.

**Comment by clehner** [comment]
Got it! I tried all 6 permutations and on the last one it appeared to work. However it looks like all the libbitcoin servers are timing out so it will have to wait to broadcast the transaction I guess.

**Comment by cpacia** [comment]
ah great. Ok I'll try to see what's going on with the servers.

**Comment by clehner** [comment]
The output transaction is broadcast and getting confirmations so it looks like the problem is resolved for this order. Thanks!

**Comment by cpacia** [comment]
Great. I pushed a patch for that bug. Hopefully it won't happen again.
