### ISSUE TITLE
Got errors installing openbazaar_1.1.2_amd64.deb

### ISSUE THREAD

**Issue by cgilliard** [OpenBazaar/OpenBazaar-Server#349]
Brief Description: 

Got the following errors:

2016-04-10 04:56:57,494 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2016-04-10 04:56:57,836 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2016-04-10 04:56:57,838 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2016-04-10 04:56:57,868 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2016-04-10 04:56:58,754 - softwarecenter.backend.reviews - WARNING - error creating bsddb: '(22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')' (corrupted?)
2016-04-10 04:56:58,754 - softwarecenter.backend.reviews - ERROR - trying to repair DB failed
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 358, in _save_review_stats_cache_blocking
    self._dump_bsddbm_for_unity(outfile, outdir)
  File "/usr/share/software-center/softwarecenter/backend/reviews/__init__.py", line 377, in _dump_bsddbm_for_unity
    0600)
DBInvalidArgError: (22, 'Invalid argument -- BDB0054 illegal flag combination specified to DB_ENV->open')
/usr/bin/software-center:184: Warning: Source ID 67 was not found when attempting to remove it
  Gtk.main()
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/utils.py", line 187, in <lambda>
    GLib.timeout_add(500, lambda: wrapper(*args, **kwargs))
  File "/usr/share/software-center/softwarecenter/utils.py", line 192, in wrapper
    f(*args, **kwargs)
  File "/usr/share/software-center/softwarecenter/ui/gtk3/app.py", line 1283, in show_app
    self.installed_pane.init_view()
  File "/usr/share/software-center/softwarecenter/ui/gtk3/panes/installedpane.py", line 143, in init_view
    self.oneconf_handler = get_oneconf_handler(self.oneconf_viewpickler)
  File "/usr/share/software-center/softwarecenter/backend/oneconfhandler/__init__.py", line 32, in get_oneconf_handler
    oneconf_handler = OneConfHandler(oneconfviewpickler)
  File "/usr/share/software-center/softwarecenter/backend/oneconfhandler/core.py", line 56, in __init__
    self.oneconf = DbusConnect()
  File "/usr/lib/python2.7/dist-packages/oneconf/dbusconnect.py", line 152, in __init__
    HOSTS_OBJECT_NAME)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process /usr/share/oneconf/oneconf-service exited with status 1
/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py:535: Warning: Source ID 20 was not found when attempting to remove it
  return super(MainContext, self).iteration(may_block)
2016-04-10 04:57:03,294 - softwarecenter.db.utils - INFO - software-center-agent finished with status 0
Traceback (most recent call last):
  File "/usr/share/software-center/softwarecenter/ui/gtk3/panes/installedpane.py", line 683, in on_db_reopen
    self._refresh_on_cache_or_db_change()
  File "/usr/share/software-center/softwarecenter/ui/gtk3/panes/installedpane.py", line 678, in _refresh_on_cache_or_db_change
    self.refresh_apps(keep_state=True)
  File "/usr/share/software-center/softwarecenter/utils.py", line 192, in wrapper
    f(*args, **kwargs)
  File "/usr/share/software-center/softwarecenter/ui/gtk3/panes/installedpane.py", line 650, in refresh_apps
    self._build_categorised_installedview(keep_state)
  File "/usr/share/software-center/softwarecenter/ui/gtk3/panes/installedpane.py", line 367, in _build_categorised_installedview
    model = self.base_model  # base model not treefilter
AttributeError: 'InstalledPane' object has no attribute 'base_model'
[19877:19877:0410/045838:ERROR:CONSOLE(0)] "Unrecognized Content-Security-Policy directive 'block-all-mixed-content'.
", source: https://github.com/openbazaar (0)

Operating System (OS and version): 

Linux chris-SH67H3 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

OpenBazaar version: 

1.1.2
Hardware: 

Linux chris-SH67H3 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Always
Steps to reproduce:
1. open package
2. 
3. 

Observed Behavior: The packages never installs and reports errors on console.

Expected Behavior:
Install correctly.

Additional info (links, images, etc go here):

**Comment by cgilliard** [comment]
When I ran this command line as root, it successfully installed.
