### ISSUE TITLE
server "Unhandled error"

### ISSUE THREAD

**Issue by lunokhod** [OpenBazaar/OpenBazaar-Server#350]
After starting the server on OSX from the command line (latest commit 97228515340006a3cd6c866b1ec4484d77b5bc55), and waiting a few minutes, I got the following error

~~~~
Unhandled Error
Traceback (most recent call last):
  File "openbazaard.py", line 266, in start
    int(args.heartbeatport), time.time())
  File "openbazaard.py", line 198, in run
    reactor.run()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/site-packages/txrudp/connection.py", line 413, in _do_send_packet
    self._proto.send_datagram(sch_packet.rudp_packet, self.relay_addr)
  File "/usr/local/lib/python2.7/site-packages/txrudp/rudp.py", line 206, in send_datagram
    self.transport.write(datagram, addr)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/udp.py", line 297, in write
    return self.socket.sendto(datagram, addr)
socket.error: [Errno 50] Network is down

2016-04-10 15:56:52+0200 [-] Unhandled Error
	Traceback (most recent call last):
	  File "openbazaard.py", line 266, in start
	    int(args.heartbeatport), time.time())
	  File "openbazaard.py", line 198, in run
	    reactor.run()
	  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
	    self.mainLoop()
	  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/site-packages/txrudp/connection.py", line 413, in _do_send_packet
	    self._proto.send_datagram(sch_packet.rudp_packet, self.relay_addr)
	  File "/usr/local/lib/python2.7/site-packages/txrudp/rudp.py", line 206, in send_datagram
	    self.transport.write(datagram, addr)
	  File "/usr/local/lib/python2.7/site-packages/twisted/internet/udp.py", line 297, in write
	    return self.socket.sendto(datagram, addr)
	socket.error: [Errno 50] Network is down
~~~~
Fortunately, this didn't crash the server. I see the error from time to time, but I have no idea what causes it.

**Comment by grzegorz-kraszewski** [comment]
Confirmed. Seems to be related with libbitcoin server: Debian Linux 8.4 on x86_64.

`
2016-04-11 09:52:50+0200 [-] [INFO] Switching to tcp://libbitcoin3.openbazaar.org:9091
2016-04-11 09:52:50+0200 [-] [ERROR] Libbitcoin server timed out. Refreshing socket and resending requests.
2016-04-11 09:52:50+0200 [-] Unhandled Error
        Traceback (most recent call last):
          File "openbazaard.py", line 266, in start
            int(args.heartbeatport), time.time())
...
`
