### ISSUE TITLE
"Unable to Connect to Your Server" [client + VPS + SSL]

### ISSUE THREAD

**Issue by NHQ** [OpenBazaar/OpenBazaar-Server#426]
Brief Description: Trying to connect client to openbazaar on VPS with SSL enabled;  client cannot connect;  while running openbazaar server (non daemon), this error printed whenever I was attempting to connect from my client.

```
2016-06-02 17:17:15-0400 [NoneType (WebSocketProtocol) (TLSMemoryBIOProtocol),1,76.102.195.134] Unhandled Error
	Traceback (most recent call last):
	  File "openbazaard.py", line 201, in run
	    reactor.run()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
	    self.mainLoop()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1206, in mainLoop
	    self.doIteration(t)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 396, in doPoll
	    log.callWithLogger(selectable, _drdw, selectable, fd, event)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 610, in _doReadOrWrite
	    self._disconnectSelectable(selectable, why, inRead)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 255, in _disconnectSelectable
	    selectable.connectionLost(f)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 293, in connectionLost
	    protocol.connectionLost(reason)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 484, in connectionLost
	    ProtocolWrapper.connectionLost(self, reason)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/policies.py", line 125, in connectionLost
	    self.wrappedProtocol.connectionLost(reason)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/policies.py", line 125, in connectionLost
	    self.wrappedProtocol.connectionLost(reason)
	exceptions.AttributeError: 'NoneType' object has no attribute 'connectionLost'
```

Operating System (OS and version): Linux Ubuntu
OpenBazaar version: 0.1
Hardware: digital ocean

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
I followed the directions here: https://slack-files.com/T02FPGBKB-F0KJU1CLX-cbbcf8a02c

**Comment by NHQ** [comment]
The good: I switched to latest build of OpenBazaar-Client, and can connect
The bad:  but not in server run as daemon
The Ugly: When I run the stop command, the server spits out:
```pidfile /tmp/openbazaard.pid does not exist. Daemon not running?```

**Comment by drwasho** [comment]
Do you have the $5/month droplet?

Before restart the server in daemon mode, run this commands:
`sudo rm /tmp/openbazaard.pid`

Should work after that. We've seen this problem repeatedly @cpacia

**Comment by NHQ** [comment]
@drwasho no such file

I get this error when I "stop" the daemon:
```pidfile /tmp/openbazaard.pid does not exist. Daemon not running?```

**Comment by drwasho** [comment]
@NHQ any luck? If not, I'll close this issue in 24 hours. Otherwise, hop onto slack.openbazaar.org so we can give you closer support.
