### ISSUE TITLE
Starting Up with VPN Issue

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Server#43]
When starting up on VPN I get this and it crashes:

```
2015-10-14 10:23:39-0400 [-] Traceback (most recent call last):
2015-10-14 10:23:39-0400 [-]   File "openbazaard.py", line 212, in <module>
2015-10-14 10:23:39-0400 [-]     Parser(OpenBazaard('/tmp/openbazaard.pid'))
2015-10-14 10:23:39-0400 [-]   File "openbazaard.py", line 161, in __init__
2015-10-14 10:23:39-0400 [-]     getattr(self, args.command)()
2015-10-14 10:23:39-0400 [-]   File "openbazaard.py", line 189, in start
2015-10-14 10:23:39-0400 [-]     run(args.testnet)
2015-10-14 10:23:39-0400 [-]   File "openbazaard.py", line 91, in run
2015-10-14 10:23:39-0400 [-]     reactor.listenUDP(port, protocol)
2015-10-14 10:23:39-0400 [-]   File "/usr/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 374, in listenUDP
2015-10-14 10:23:39-0400 [-]     p.startListening()
2015-10-14 10:23:39-0400 [-]   File "/usr/local/lib/python2.7/site-packages/twisted/internet/udp.py", line 175, in startListening
2015-10-14 10:23:39-0400 [-]     self._bindSocket()
2015-10-14 10:23:39-0400 [-]   File "/usr/local/lib/python2.7/site-packages/twisted/internet/udp.py", line 193, in _bindSocket
2015-10-14 10:23:39-0400 [-]     skt.bind((self.interface, self.port))
2015-10-14 10:23:39-0400 [-]   File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
2015-10-14 10:23:39-0400 [-]     return getattr(self._sock,name)(*args)
2015-10-14 10:23:39-0400 [-] TypeError: an integer is required
```

**Comment by hoffmabc** [comment]
Also it starts with this message:

```
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
 /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
        \/|__|        \/     \/       \/      \/      \/     \/     \/

OpenBazaar Server v0.1 starting...
2015-10-14 10:25:48-0400 [-] Log opened.
2015-10-14 10:25:48-0400 [-] Finding NAT Type..
2015-10-14 10:25:56-0400 [-] Blocked on None:None
```

Looks like no IP:Port found.
