### ISSUE TITLE
File "openbazaard.py", line 12, in <module>     from api.restapi import RestAPI

### ISSUE THREAD

**Issue by Rocks333** [OpenBazaar/OpenBazaar-Server#442]
I have latest version installed on a fresh Ubuntu 14.04 VPS.
It was running fine for few days. Yesterday I decided to run it again and got this:

`~/OpenBazaar-Server$ python openbazaard.py start -da 0.0.0.0
Traceback (most recent call last):
  File "openbazaard.py", line 12, in <module>
    from api.restapi import RestAPI
  File "/home/openb/OpenBazaar-Server/api/restapi.py", line 26, in <module>
    from market.contracts import Contract, check_order_for_payment
  File "/home/openb/OpenBazaar-Server/market/contracts.py", line 13, in <module>
    from bitcoin import SelectParams
ImportError: cannot import name SelectParams
`

i haven't touched anything on this server in between when it was running fine and this.

**Comment by Rocks333** [comment]
actually I might have installed openvpn in between both runs but don't see how this could have broken OB?

**Comment by hoffmabc** [comment]
Are you using a virtualenv?

**Comment by Rocks333** [comment]
well it's running on a VPS

**Comment by hoffmabc** [comment]
What is this issue?

**Comment by hoffmabc** [comment]
Have you done 
```
pip install -r requirements.txt
```

**Comment by Rocks333** [comment]
I think I did use that during the installation. The installation went fine and it was working for few days.
I just ran this command again and here is what I got

> ~/OpenBazaar-Server$ pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): protobuf==3.0.0b2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Twisted==16.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): txrudp==0.5.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pystun==0.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): bitcointools==1.1.44 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): gnupg==2.0.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): pynacl==1.0.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): txrestapi==0.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): txws==0.9.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): python-libbitcoinclient==0.4.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): python-bitcoinlib==0.5.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): pyopenssl==0.15.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): miniupnpc==1.9 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): bleach==1.4.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): service_identity in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): zope.interface>=3.6.0 in /usr/local/lib/python2.7/dist-packages (from Twisted==16.1.0->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/local/lib/python2.7/dist-packages (from txrudp==0.5.1->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): psutil>=1.2.1 in /usr/local/lib/python2.7/dist-packages (from gnupg==2.0.2->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from pynacl==1.0.1->-r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.1.0 in /usr/local/lib/python2.7/dist-packages (from pynacl==1.0.1->-r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): ecdsa in /usr/local/lib/python2.7/dist-packages (from python-libbitcoinclient==0.4.3->-r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): pyzmq in /usr/local/lib/python2.7/dist-packages (from python-libbitcoinclient==0.4.3->-r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/dist-packages (from zope.interface>=3.6.0->Twisted==16.1.0->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.1.0->pynacl==1.0.1->-r requirements.txt (line 7))
Cleaning up...
openb@1919-4187:~/OpenBazaar-Server$ sudo python openbazaard.py start -da 0.0.0.0
Traceback (most recent call last):
  File "openbazaard.py", line 12, in <module>
    from api.restapi import RestAPI
  File "/home/openb/OpenBazaar-Server/api/restapi.py", line 26, in <module>
    from market.contracts import Contract, check_order_for_payment
  File "/home/openb/OpenBazaar-Server/market/contracts.py", line 13, in <module>

**Comment by pineli** [comment]
I have the same problem...

$ python openbazaard.py start -a 0.0.0.0
Traceback (most recent call last):
  File "openbazaard.py", line 11, in <module>
    from api.ws import WSFactory, AuthenticatedWebSocketProtocol, AuthenticatedWebSocketFactory
  File "/home/.../OpenBazaar-Server/api/ws.py", line 10, in <module>
    import nacl.encoding
ImportError: No module named nacl.encoding

**Comment by stanlog** [comment]
Hello, I have the same issue after a reboot of my VM without stopping openbazaard. I tried to update Openbazaar-server with a git pull and a pip install, same errors:
`Traceback (most recent call last):
  File "openbazaard.py", line 12, in <module>
    from api.restapi import RestAPI
  File "/home/stanlog/OpenBazaar-Server/api/restapi.py", line 28, in <module>
    from market.contracts import Contract, check_order_for_payment
  File "/home/stanlog/OpenBazaar-Server/market/contracts.py", line 13, in <module>
    from bitcoin import SelectParams
ImportError: cannot import name SelectParams`

I hope the reason isn't the fact the db is corrupted. If that's the case, is there a command to repair it ?

Have you got any idea ? Is these tests to do to report you logs ? Thank you for your help.
