### ISSUE TITLE
Can't get daemon to start: ImportError: cannot import name encodings

### ISSUE THREAD

**Issue by fusenn** [OpenBazaar/OpenBazaar-Server#469]
Brief Description: trying to start openbazaard, getting error

Operating System (OS and version): ubuntu 16.04
OpenBazaar version: latest
Hardware: vps

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
always

Steps to reproduce:
1. clone/git pull
2. install requirements
3. start daemon

Observed Behavior:
error message

Expected Behavior:
daemon to start

Additional info (links, images, etc go here):
Been fighting with error msgs all night when trying to start daemon. When i fix one, another pops up.

Console log:

Traceback (most recent call last):
  File "openbazaard.py", line 11, in <module>
    from api.ws import WSFactory, AuthenticatedWebSocketProtocol, AuthenticatedWebSocketFactory
  File "/home/fusenn/OpenBazaar-Server/api/ws.py", line 15, in <module>
    from api.utils import smart_unicode, sanitize_html
  File "/home/fusenn/OpenBazaar-Server/api/utils.py", line 1, in <module>
    import bleach
  File "/usr/local/lib/python2.7/dist-packages/bleach/__init__.py", line 8, in <module>
    from html5lib.sanitizer import HTMLSanitizer
  File "/usr/local/lib/python2.7/dist-packages/html5lib/sanitizer.py", line 7, in <module>
    from .tokenizer import HTMLTokenizer
  File "/usr/local/lib/python2.7/dist-packages/html5lib/tokenizer.py", line 17, in <module>
    from .inputstream import HTMLInputStream
  File "/usr/local/lib/python2.7/dist-packages/html5lib/inputstream.py", line 9, in <module>
    from .constants import encodings, ReparseException
ImportError: cannot import name encodings

Anybody got any idea? Can't seem to get rid of this error message.

**Comment by fusenn** [comment]
Fixed this by changing from 16.04 to 14.04, nothing else worked.

**Comment by tianfan** [comment]
hey dude. no need to do that. you just need to change the line in python2.7/site-packages/html5lib/inputstream.py

from
from .constants import encodings, ReparseException

to
from .constants import *
