### ISSUE TITLE
KeyError 0801 - error on startup

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Server#50]
```
OpenBazaar Server v0.1 starting...
2015-10-21 21:11:57+1000 [-] Log opened.
2015-10-21 21:11:57+1000 [-] Finding NAT Type..
2015-10-21 21:11:58+1000 [-] Traceback (most recent call last):
2015-10-21 21:11:58+1000 [-]   File "openbazaard.py", line 217, in <module>
2015-10-21 21:11:58+1000 [-]     Parser(OpenBazaard('/tmp/openbazaard.pid'))
2015-10-21 21:11:58+1000 [-]   File "openbazaard.py", line 166, in __init__
2015-10-21 21:11:58+1000 [-]     getattr(self, args.command)()
2015-10-21 21:11:58+1000 [-]   File "openbazaard.py", line 194, in start
2015-10-21 21:11:58+1000 [-]     run(args.testnet)
2015-10-21 21:11:58+1000 [-]   File "openbazaard.py", line 50, in run
2015-10-21 21:11:58+1000 [-]     response = stun.get_ip_info(stun_host="seed.openbazaar.org", source_port=port)
2015-10-21 21:11:58+1000 [-]   File "C:\Python27\lib\site-packages\stun\__init__.py", line 253, in get_ip_info
2015-10-21 21:11:58+1000 [-]     stun_host=stun_host, stun_port=stun_port)
2015-10-21 21:11:58+1000 [-]   File "C:\Python27\lib\site-packages\stun\__init__.py", line 219, in get_nat_type
2015-10-21 21:11:58+1000 [-]     changeRequest)
2015-10-21 21:11:58+1000 [-]   File "C:\Python27\lib\site-packages\stun\__init__.py", line 136, in stun_test
2015-10-21 21:11:58+1000 [-]     bind_resp_msg = dictValToMsgType[msgtype] == "BindResponseMsg"
2015-10-21 21:11:58+1000 [-] KeyError: '0801'
```

**Comment by drwasho** [comment]
Only encountered this bug when I attempted to start the server with my VPN on.

**Comment by cpacia** [comment]
This is issue #44
