### ISSUE TITLE
Ubuntu 14.04 in Virtualbox, startup: ValueError: database parameter must be string or APSW Connection object

### ISSUE THREAD

**Issue by AronVanAmmers** [OpenBazaar/OpenBazaar-Server#52]
On first start I get this:

```
aron@thewire:~/Development/OpenBazaar/OpenBazaar-Server$ python openbazaard.py start
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
 /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ 
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
        \/|__|        \/     \/       \/      \/      \/     \/     \/

OpenBazaar Server v0.1 starting...
Generating GUID, stand by...
2015-10-22 23:25:28+0200 [OpenBazaard] [INFO] Finding NAT Type...
2015-10-22 23:25:28+0200 [OpenBazaard] [INFO] Full Cone on 82.171.248.183:61627
Traceback (most recent call last):
  File "openbazaard.py", line 236, in <module>
    Parser(OpenBazaard('/tmp/openbazaard.pid'))
  File "openbazaard.py", line 174, in __init__
    getattr(self, args.command)()
  File "openbazaard.py", line 213, in start
    run(args.testnet, args.loglevel, port, args.restallowip, args.wsallowip)
  File "openbazaard.py", line 82, in run
    storage = ForgetfulStorage() if TESTNET else PersistentStorage(db)
  File "/home/aron/Development/OpenBazaar/OpenBazaar-Server/dht/storage.py", line 144, in __init__
    self.db = lite.connect(filename)
ValueError: database parameter must be string or APSW Connection object
```

Second start, only "Generating GUID" is missing:

```
aron@thewire:~/Development/OpenBazaar/OpenBazaar-Server$ python openbazaard.py start
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
 /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ 
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
        \/|__|        \/     \/       \/      \/      \/     \/     \/

OpenBazaar Server v0.1 starting...
2015-10-22 23:25:37+0200 [OpenBazaard] [INFO] Finding NAT Type...
2015-10-22 23:25:37+0200 [OpenBazaard] [INFO] Full Cone on 82.171.248.183:61627
Traceback (most recent call last):
  File "openbazaard.py", line 236, in <module>
    Parser(OpenBazaard('/tmp/openbazaard.pid'))
  File "openbazaard.py", line 174, in __init__
    getattr(self, args.command)()
  File "openbazaard.py", line 213, in start
    run(args.testnet, args.loglevel, port, args.restallowip, args.wsallowip)
  File "openbazaard.py", line 82, in run
    storage = ForgetfulStorage() if TESTNET else PersistentStorage(db)
  File "/home/aron/Development/OpenBazaar/OpenBazaar-Server/dht/storage.py", line 144, in __init__
    self.db = lite.connect(filename)
ValueError: database parameter must be string or APSW Connection object
```

**Comment by cpacia** [comment]
Good catch. I just changed that line like 10 mins ago and forgot to put `db.DATABASE`. That would only have fired on the mainnet and we're only using testnet right now.

As for the guid. It only generates it the first time.

**Comment by AronVanAmmers** [comment]
That helps, thanks.

**Comment by AronVanAmmers** [comment]
So seeing what I should see now:

```
aron@thewire:~/Development/OpenBazaar/OpenBazaar-Server$ python openbazaard.py start
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
 /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ 
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
        \/|__|        \/     \/       \/      \/      \/     \/     \/

OpenBazaar Server v0.1 starting...
2015-10-22 23:48:43+0200 [OpenBazaard] [INFO] Finding NAT Type...
2015-10-22 23:48:43+0200 [OpenBazaard] [INFO] Full Cone on 82.171.248.183:62229
2015-10-22 23:48:43+0200 [Server] [INFO] querying seed.openbazaar.org:8080 for peers
2015-10-22 23:48:45+0200 [Server] [ERROR] failed to query seed: [Errno 111] Connection refused
2015-10-22 23:48:46+0200 [OpenBazaard] [INFO] Libbitcoin server online
```

**Comment by cpacia** [comment]
yeah I had to force push because I messed up the last commit. Make sure you are up to date. And also run python openbazaard.py start --testnet
