### ISSUE TITLE
pip ImportError: No module named setuptools_ext

### ISSUE THREAD

**Issue by martinvahi** [OpenBazaar/OpenBazaar-Server#523]
Downloading/unpacking gnupg==2.0.2 (from -r ./requirements.txt (line 6))
      Downloading gnupg-2.0.2.tar.gz (97kB): 97kB downloaded
      Running setup.py (path:/tmp/pip-build-JIDDJ1/gnupg/setup.py) egg_info for package gnupg
        
    Downloading/unpacking pynacl==1.0.1 (from -r ./requirements.txt (line 7))
      Downloading PyNaCl-1.0.1.tar.gz (2.7MB): 2.7MB downloaded
      Running setup.py (path:/tmp/pip-build-JIDDJ1/pynacl/setup.py) egg_info for package pynacl
        
        Installed /tmp/pip-build-JIDDJ1/pynacl/cffi-1.10.0-py2.7-linux-x86_64.egg
        Traceback (most recent call last):
          File "<string>", line 17, in <module>
          File "/tmp/pip-build-JIDDJ1/pynacl/setup.py", line 259, in <module>
            "Programming Language :: Python :: 3.5",
          File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
            _setup_distribution = dist = klass(attrs)
          File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__
            _Distribution.__init__(self,attrs)
          File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
            self.finalize_options()
          File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options
            ep.load()(self, ep.name, value)
          File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
            ['__name__'])
        ImportError: No module named setuptools_ext
        Complete output from command python setup.py egg_info:
        
    
    Installed /tmp/pip-build-JIDDJ1/pynacl/cffi-1.10.0-py2.7-linux-x86_64.egg
    
    Traceback (most recent call last):
    
      File "<string>", line 17, in <module>
    
      File "/tmp/pip-build-JIDDJ1/pynacl/setup.py", line 259, in <module>
    
        "Programming Language :: Python :: 3.5",
    
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    
        _setup_distribution = dist = klass(attrs)
    
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__
    
        _Distribution.__init__(self,attrs)
    
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    
        self.finalize_options()
    
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options
    
        ep.load()(self, ep.name, value)
    
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    
        ['__name__'])
    
    ImportError: No module named setuptools_ext
    
    ----------------------------------------
                                                                                    
    Cleaning up...

Environment:

    openbazaar_01@mvahi:~/large_files/tv_01a/OpenBazaar-Server$ uname -a
    Linux mvahi 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
    openbazaar_01@mvahi:~/large_files/tv_01a/OpenBazaar-Server$ python --version
    Python 2.7.9
    openbazaar_01@mvahi:~/large_files/tv_01a/OpenBazaar-Server$ date
    L märts 25 14:58:14 EET 2017
    openbazaar_01@mvahi:~/large_files/tv_01a/OpenBazaar-Server$

**Comment by ptman** [comment]
Upgrade cffi
