### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

### ISSUE THREAD

**Issue by bladedoyle** [OpenBazaar/OpenBazaar-Server#531]
Brief Description: 

Error when starting server (or even getting help message)

Operating System (OS and version): linux, ubuntu, 4.4.0-83-generic
OpenBazaar version: (HEAD detached at v0.2.6)
Hardware:  Intel

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce):   Always

Steps to reproduce:
1. Install depends
2. clone openbazaar-server git repo and check out v0.2.6 tag
3. Manually apply fix described in issue #521 
4. Run:  python openbazaard.py start --help

Observed Behavior:
Traceback (most recent call last):
  File "openbazaard.py", line 12, in <module>
    from api.restapi import RestAPI
  File "/ob/OpenBazaar-Server/api/restapi.py", line 5, in <module>
    import obelisk
  File "/usr/local/lib/python2.7/dist-packages/obelisk/__init__.py", line 3, in <module>
    from client import *
  File "/usr/local/lib/python2.7/dist-packages/obelisk/client.py", line 3, in <module>
    from zmqbase import ClientBase
  File "/usr/local/lib/python2.7/dist-packages/obelisk/zmqbase.py", line 11, in <module>
    from twisted.internet import defer, reactor
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/default.py", line 44, in _getInstallFunction
    from twisted.internet.epollreactor import install
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 24, in <module>
    from twisted.internet import posixbase
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 29, in <module>
    from twisted.internet._newtls import (
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 41, in <module>
    from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 124, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

Expected Behavior:

the help message

Additional info (links, images, etc go here):

none

**Comment by bladedoyle** [comment]
Ah, this is fixed by using pyopenssl==16.2.0
(probably needs to be updated in requirements.txt)

**Comment by spanwair-r** [comment]
find whitch version of pyopenssl you have (maybe in this time 17.3.0)
open requirements.txt in the folder /home/OpenBazaar-server - open folder in termninal
through terminal write sudo gedit requirements.txt and update your pyopenssl==17.3.0 (depend on your current python version)
save and run open bazaar command again / its should to work, atleast worked for me

**Comment by vhosakot** [comment]
I saw the `AttributeError: 'module' object has no attribute 'SSL_ST_INIT'` error too and `sudo pip install pyOpenSSL==16.2.0` resolved it for me!
