### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by bladedoyle** [OpenBazaar/OpenBazaar-Server#532]
Brief Description: 

Starting the server fails with:  ImportError: No module named requests

Operating System (OS and version): linux
OpenBazaar version: master
Hardware: intel

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 

Always

Steps to reproduce:
1.  install depends
2. clone the openbazaar server git repo
3. checkout master
4. manually apply fixes for existing issues #521 and #531
5. run python openbazaard.py start

Observed Behavior:
Traceback (most recent call last):
  File "openbazaard.py", line 12, in <module>
    from api.restapi import RestAPI
  File "/ob/OpenBazaar-Server/api/restapi.py", line 32, in <module>
    from market.migration import migratev2
  File "/ob/OpenBazaar-Server/market/migration.py", line 8, in <module>
    import requests
ImportError: No module named requests

Expected Behavior:

the server should start

Additional info (links, images, etc go here):

**Comment by bladedoyle** [comment]
Please add additional module depend "requests-2.18.1" to project requirements.txt

**Comment by bladedoyle** [comment]
This is a duplicate of #528
