### ISSUE TITLE
exceptions.TypeError: rpc_ping() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Server#54]
With newest code I got this on startup. The server kept running.

I deleted database and ran it again, didn't see the error anymore.

````
2015-10-26 07:00:56-0400 [OpenBazaarProtocol (UDP)] Unhandled error in Deferred:
Unhandled error in Deferred:
2015-10-26 07:00:56-0400 [OpenBazaarProtocol (UDP)] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/txrudp/connection.py", line 566, in _pop_received_packet
	    self.handler.receive_message(payload)
	  File "/home/nondescript/testingrepos/OpenBazaar-Server/wireprotocol.py", line 70, in receive_message
	    processor.receive_message(datagram, self.connection)
	  File "/home/nondescript/testingrepos/OpenBazaar-Server/rpcudp.py", line 94, in receive_message
	    self._acceptRequest(msgID, str(Command.Name(m.command)).lower(), data, sender, connection)
	  File "/home/nondescript/testingrepos/OpenBazaar-Server/rpcudp.py", line 115, in _acceptRequest
	    d = defer.maybeDeferred(f, sender, *args)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 139, in maybeDeferred
	    result = f(*args, **kw)
	exceptions.TypeError: rpc_ping() takes exactly 2 arguments (3 given)
	
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/txrudp/connection.py", line 566, in _pop_received_packet
    self.handler.receive_message(payload)
  File "/home/nondescript/testingrepos/OpenBazaar-Server/wireprotocol.py", line 70, in receive_message
    processor.receive_message(datagram, self.connection)
  File "/home/nondescript/testingrepos/OpenBazaar-Server/rpcudp.py", line 94, in receive_message
    self._acceptRequest(msgID, str(Command.Name(m.command)).lower(), data, sender, connection)
  File "/home/nondescript/testingrepos/OpenBazaar-Server/rpcudp.py", line 115, in _acceptRequest
    d = defer.maybeDeferred(f, sender, *args)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 139, in maybeDeferred
    result = f(*args, **kw)
exceptions.TypeError: rpc_ping() takes exactly 2 arguments (3 given)
2015-10-26 07:00:56-0400 [OpenBazaard] [INFO] bootstrap complete, downloading outstanding messages...
````

**Comment by cpacia** [comment]
Fixed
