### ISSUE TITLE
Ubuntu Installation Fail

### ISSUE THREAD

**Issue by christroutner** [OpenBazaar/OpenBazaar-Server#546]
Brief Description: 
I tried installing the master branch branch on my Ubuntu box. Both the Docker container *and* the build according to [these ubuntu instructions](https://github.com/OpenBazaar/OpenBazaar-Server/wiki/How-to-install-on-Ubuntu) failed in the same way. Details below.

Operating System (OS and version): 16.04
OpenBazaar version: [OpenBazaar-Server master branch at b5e6d38](https://github.com/OpenBazaar/OpenBazaar-Server/tree/b5e6d38160d41b9155d5b6bec8b5e2cee4ce77d1)
Hardware: VirtualBox on Windows 10 running Ubuntu VM

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): **Always**

Steps to reproduce:
1. Running the Docker image with Compose generated the following errors:

```
...
************* Module market.contracts
market/contracts.py:1477: [I:locally-disabled] -- Locally disabling unused-variable (W0612)
market/contracts.py:1478: [I:locally-disabled] -- Locally disabling cell-var-from-loop (W0640)
************* Module market.migration
market/migration.py: 93: [C:line-too-long] -- Line too long (141/116)
market/migration.py:131: [C:line-too-long] -- Line too long (119/116)
market/migration.py:  8: [W:unused-import] -- Unused import requests
************* Module market.transactions
market/transactions.py:174: [I:locally-disabled] -- Locally disabling cell-var-from-loop (W0640)
************* Module market.network
market/network.py:850: [I:locally-disabled] -- Locally disabling unused-variable (W0612)
make: *** [pycheck] Error 1
FAIL: Detected 3 files with errors.
Makefile:14: recipe for target 'pycheck' failed
ERROR: Service 'openbazaard' failed to build: The command '/bin/sh -c make' returned a non-zero code: 2
```
2. Running the [instructions for installing on Ubuntu](https://github.com/OpenBazaar/OpenBazaar-Server/wiki/How-to-install-on-Ubuntu) generated nearly the same error messages. Below is the tail end of running `make`, and then trying to run the Bazaar server:

```
...
************* Module market.contracts
market/contracts.py:1477: [I:locally-disabled] -- Locally disabling unused-variable (W0612)
market/contracts.py:1478: [I:locally-disabled] -- Locally disabling cell-var-from-loop (W0640)
************* Module market.migration
market/migration.py: 17: [C:line-too-long] -- Line too long (117/116)
market/migration.py: 20: [C:line-too-long] -- Line too long (118/116)
market/migration.py: 22: [C:line-too-long] -- Line too long (118/116)
market/migration.py: 87: [C:line-too-long] -- Line too long (141/116)
market/migration.py:125: [C:line-too-long] -- Line too long (119/116)
market/migration.py:  8: [W:unused-import] -- Unused import requests
************* Module market.transactions
market/transactions.py:174: [I:locally-disabled] -- Locally disabling cell-var-from-loop (W0640)
************* Module market.network
market/network.py:850: [I:locally-disabled] -- Locally disabling unused-variable (W0612)
FAIL: Detected 3 files with errors.
Makefile:14: recipe for target 'pycheck' failed
make: *** [pycheck] Error 1
trout@trout-VirtualBox:~/work/openBazaar/openBazaar-server$ python openbazaard.py start --testnet
Traceback (most recent call last):
  File "openbazaard.py", line 12, in <module>
    from api.restapi import RestAPI
  File "/home/trout/work/openBazaar/openBazaar-server/api/restapi.py", line 5, in <module>
    import obelisk
  File "/usr/local/lib/python2.7/dist-packages/obelisk/__init__.py", line 3, in <module>
    from client import *
  File "/usr/local/lib/python2.7/dist-packages/obelisk/client.py", line 3, in <module>
    from zmqbase import ClientBase
  File "/usr/local/lib/python2.7/dist-packages/obelisk/zmqbase.py", line 11, in <module>
    from twisted.internet import defer, reactor
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/default.py", line 44, in _getInstallFunction
    from twisted.internet.epollreactor import install
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 24, in <module>
    from twisted.internet import posixbase
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 29, in <module>
    from twisted.internet._newtls import (
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 41, in <module>
    from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 124, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
trout@trout-VirtualBox:~/work/openBazaar/openBazaar-server$ 
```

**Comment by christroutner** [comment]
# Update:

I was able to get the server to run on Ubuntu [using the fix in this issue](https://github.com/OpenBazaar/OpenBazaar-Server/issues/531)
