### ISSUE TITLE
_showImage error in REST API

### ISSUE THREAD

**Issue by hoffmabc** [OpenBazaar/OpenBazaar-Server#58]
I received this backtrace when trying to view an image in the client.

```
Unhandled Error
Traceback (most recent call last):
  File "/Users/brianhoffman/t/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 382, in callback
    self._startRunCallbacks(result)
  File "/Users/brianhoffman/t/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
    self._runCallbacks()
  File "/Users/brianhoffman/t/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 577, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/brianhoffman/t/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1237, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/Users/brianhoffman/t/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
    result = g.send(result)
  File "/Users/brianhoffman/t/OpenBazaar-Server/api/restapi.py", line 69, in _showImage
    request.finish()
  File "/Users/brianhoffman/t/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/web/server.py", line 228, in finish
    return http.Request.finish(self)
  File "/Users/brianhoffman/t/OpenBazaar-Server/env/lib/python2.7/site-packages/twisted/web/http.py", line 930, in finish
    "Request.finish called on a request after its connection was lost; "
exceptions.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
```

**Comment by cpacia** [comment]
That's say the TCP connection to the api was lost before the api could respond. You probably had a bad Internet connection.
