### ISSUE TITLE
pyopenssl misbehaving

### ISSUE THREAD

**Issue by unsystemizer** [OpenBazaar/OpenBazaar-Server#62]
I don't know why I appear to be the only one with this problem, but here it is:
```
$ python openbazaard.py start
Traceback (most recent call last):
  File "openbazaard.py", line 12, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 73, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

$ sudo pip list | grep urllib
urllib3 (1.12)

$ sudo pip3 list | grep urllib
urllib3 (1.12)

$ cat /etc/debian_version
stretch/sid

```

**Comment by unsystemizer** [comment]
It's an upstream issue so I'll close this and use Ubuntu 14.04 instead.

**Comment by z3ntu** [comment]
I have the same error on Ubuntu 15.10.

> luca@luca-G550JK:~/Programs/OpenBazaar-Server$ python2.7 openbazaard.py
Traceback (most recent call last):
  File "openbazaard.py", line 11, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 73, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
luca@luca-G550JK:~/Programs/OpenBazaar-Server$ python2.7 openbazaard.py start
Traceback (most recent call last):
  File "openbazaard.py", line 11, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 73, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

**Comment by unsystemizer** [comment]
In any case, it's not an OB problem so it should be filled upstream.
