### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by SamPatt** [OpenBazaar/OpenBazaar-Server#68]
I got this error after running 'python openbazaard.py stop' and then restarting the server. Happened twice in a row but was fine the third time.

```
OpenBazaar Server v0.1 starting...
2015-11-04 09:55:11-0500 [OpenBazaard] [INFO] Finding NAT Type...
2015-11-04 09:55:11-0500 [OpenBazaard] [INFO] Full Cone on 97.84.133.102:28467
Traceback (most recent call last):
  File "openbazaard.py", line 237, in <module>
    Parser(OpenBazaard('/tmp/openbazaard.pid'))
  File "openbazaard.py", line 175, in __init__
    getattr(self, args.command)()
  File "openbazaard.py", line 214, in start
    run(args.testnet, args.loglevel, port, args.restallowip, args.wsallowip)
  File "openbazaard.py", line 104, in run
    reactor.listenUDP(port, protocol)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 374, in listenUDP
    p.startListening()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/udp.py", line 175, in startListening
    self._bindSocket()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/udp.py", line 195, in _bindSocket
    raise error.CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on any:28467: [Errno 98] Address already in use.
```

**Comment by cpacia** [comment]
you just restarted too quickly
