### ISSUE TITLE
google.protobuf.message.DecodeError: Truncated message.

### ISSUE THREAD

**Issue by insanity54** [OpenBazaar/OpenBazaar-Server#78]
ob server fails to start. 

My environment is Trisquel. It worked a few commits back, I'm doing some testing to see which commit broke it for me.

```
$ python openbazaard.py start
________                      __________
\_____  \ ______   ____   ____\______   \_____  _____________  _____ _______
 /   |   \\____ \_/ __ \ /    \|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ 
/    |    \  |_> >  ___/|   |  \    |   \ / __ \_/    /  / __ \_/ __ \|  | \/
\_______  /   __/ \___  >___|  /______  /(____  /_____ \(____  (____  /__|
        \/|__|        \/     \/       \/      \/      \/     \/     \/

OpenBazaar Server v0.1 starting...
2015-11-16 14:03:36-0800 [OpenBazaard] [INFO] Finding NAT Type...
2015-11-16 14:03:45-0800 [OpenBazaard] [INFO] Restric NAT on 184.97.64.11:18467
Traceback (most recent call last):
  File "openbazaard.py", line 273, in <module>
    Parser(OpenBazaard('/tmp/openbazaard.pid'))
  File "openbazaard.py", line 208, in __init__
    getattr(self, args.command)()
  File "openbazaard.py", line 250, in start
    run(args.testnet, args.loglevel, port, args.restallowip, args.wsallowip, args.ssl)
  File "openbazaard.py", line 85, in run
    node = Node(keys.guid, ip_address, port, signed_pubkey=keys.guid_signed_pubkey, vendor=Profile(db).get().vendor)
  File "/home/rabbit/scripts/openbazaar/OpenBazaar-Server/market/profile.py", line 18, in __init__
    self.profile.ParseFromString(self.db.get_proto())
  File "/home/rabbit/scripts/openbazaar/OpenBazaar-Server/observer/local/lib/python2.7/site-packages/google/protobuf/message.py", line 186, in ParseFromString
    self.MergeFromString(serialized)
  File "/home/rabbit/scripts/openbazaar/OpenBazaar-Server/observer/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 841, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/home/rabbit/scripts/openbazaar/OpenBazaar-Server/observer/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 874, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/home/rabbit/scripts/openbazaar/OpenBazaar-Server/observer/local/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 654, in DecodeField
    if value._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/home/rabbit/scripts/openbazaar/OpenBazaar-Server/observer/local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 866, in InternalParse
    new_pos = local_SkipField(buffer, new_pos, end, tag_bytes)
  File "/home/rabbit/scripts/openbazaar/OpenBazaar-Server/observer/local/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 827, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "/home/rabbit/scripts/openbazaar/OpenBazaar-Server/observer/local/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 768, in _SkipLengthDelimited
    raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
```

**Comment by cpacia** [comment]
you might need to delete the database and start over

**Comment by insanity54** [comment]
Oh how do I do that? What kind of database does it use?

**Comment by SamPatt** [comment]
In the OpenBazaar directory there is an OB-Testnet.db file as well as a cache.pickle file. Delete them both. Then restart in the testnet. It will make a new GUID and database.

**Comment by insanity54** [comment]
I don't see either of those files. This is the first run after cloning the repo to a clean directory, if that has anything to do with it.

**Comment by SamPatt** [comment]
The directory must exist somewhere; your log shows that a GUID has been generated.

First, you need to run with this command to use the testnet:

```
python openbazaard.py start --testnet
```
Search for OB.db or cache.pickle and delete them.

What's your OS?

**Comment by insanity54** [comment]
Ah, `--testnet`. It runs when I added that.

My OS is Trisquel 7, which is an ubuntu derivative.

I get it now, there's a data directory `~/OpenBazaar`, separate from the source directory. I should have realized.

I deleted ~/OpenBazaar/cache.pickle and ~/OpenBazaar/OB-Mainnet.db, then did

`python openbazaard.py start --testnet`

Success.

`python openbazaard.py start`

Success!

**Comment by SamPatt** [comment]
Excellent, glad to help. Keep opening issues for stuff like this, it'll help future folks who run into problems like these.

**Comment by insanity54** [comment]
Cool beans, will do. Thank you very much!

On Mon, Nov 16, 2015 at 5:03 PM, Sam Patterson <notifications@github.com>
wrote:

> Excellent, glad to help. Keep opening issues for stuff like this, it'll
> help future folks who run into problems like these.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenBazaar/OpenBazaar-Server/issues/78#issuecomment-157225771>
> .
>



-- 
http://grimtech.net/ <http://grimtech.net/about>
