### ISSUE TITLE
Restricted NAT stop-start issues

### ISSUE THREAD

**Issue by drwasho** [OpenBazaar/OpenBazaar-Server#79]
I've only noticed this with my local node, which is behind a restricted NAT: if I shutdown the server properly, and immediately try and restart it, then I get the `TypeError: an integer is required`. I have to wait 5-10 minutes before trying again.

Can someone else confirm this is an issue for nodes behind a Restricted NAT?

Now I could switch to another port, but then the client has to go through 10 failed attempts before I have access to the Admin panel to try and change the port number. 

The UX problem is that users will now know how to change the port, they'll just keep trying and failing to get the application started.

If we code into the server a random port selection if the default port is unavailable, how we can communicate this to the client without having requiring the user to input the port or without the failed attempts?

Ping @jjeffryes

**Comment by cpacia** [comment]
I don't understand any of that. 

> I've only noticed this with my local node, which is behind a restricted NAT: if I shutdown the server properly, and immediately try and restart it, then I get the TypeError: an integer is required. I have to wait 5-10 minutes before trying again.

There is some kind of error starting up on that port. I don't know what causes it, but I've never seen it take 5-10 minutes. More like 5-10 seconds.

> Now I could switch to another port, but then the client has to go through 10 failed attempts before I have access to the Admin panel to try and change the port number.

Why do you need to change the port in the admin panel? And what is the 10 attempts all about.

**Comment by jjeffryes** [comment]
I have the exact same problem, after shutting down the server I have to wait several minutes before I can start it up again successfully. 

The 10 tries thing is what the client does when it can't connect to the server. If you shut down the server and start it up again immediately, it will fail to start. The client will attempt to connect to the server 10 times (which is an arbitrary number, we should probably set it to 3 or something) before telling you it can't reach the server. 

After the client gives up trying to reach the server you can access the server settings to change the port number. There's a pending issue to show an option to change the server sooner than that.

**Comment by drwasho** [comment]
It takes 5-10 seconds on my VPS. Now the only 2 differences between my VPS and local machine are: 1) one is Ubuntu, the other is Windows, and 2) one has a full cone, the other is a restricted NAT. 

Josh, what type of NAT do you have?

**Comment by cpacia** [comment]
How are you changing the port in the client? That is a command line setting on the server and there is no api call to set that.

**Comment by jjeffryes** [comment]
I have no idea what kind of NAT I have. Whatever comes default from Verizon.

**Comment by drwasho** [comment]
I don't change the port on the client, I do it in the terminal after the server fails to start.

**Comment by drwasho** [comment]
@jjeffreys when you start the server it should tell you the type in the first few lines in the terminal.

**Comment by cpacia** [comment]
> Edit: if I need to change the port in the terminal, I wait until the 10 failed attempts have cycled through in the client, go to the admin panel and change the port number so that the client can talk to the server.

Change what port number? There is no server option to change the api ports

**Comment by drwasho** [comment]
Step 1: try to run the openbazaar server from the terminal shortly after shutting down properly (ie via the shutdown REST api).. It fails, returning the error in the OP. After several minutes, it returns the same error.


Step 2: I change the port number

`python openbazaard.py start -t -p [random port number]`

Step 3: I open up the client. The client, using the default server settings (`localhost:18469`) cannot reach the server and goes through 10 attempted reconnects before going to a blank home screen.

Step 4: I go to the admin panel of the client, and change the port number of the server location to then number I ran the server with in step 2.

---

The issue here is that it's not taking 5-10 seconds to reconnect on the same port for some machines. I think it may be due to the fact that I'm using a restricted NAT, because I don't see the same error on my VPS. That's just a theory though. Could be because of Windows or something else.

**Comment by cpacia** [comment]
the -p setting is the port for openbazaar network traffic, not api traffic. 

Changing the port in the admin panel to the port you set with -p should not work.

**Comment by drwasho** [comment]
My misunderstanding, you're right - I don't have to change the port number in the client in a random port is selected when starting the server.

After a bit of testing I'm seeing some strange results, which I've pasted below. Basically it seems to alternate between `full cone` and `restricted NAT` when I stop-start the server. Sometimes it throws the integer error, so I switch to a random port, and then switch back to default.

```
2015-11-18 11:45:16+1000 [ConnHandler] [INFO] connected to 173.79.161.229:45545
2015-11-18 11:45:28+1000 [ConnHandler] [INFO] connection with 104.131.6.245:28467 terminated
2015-11-18 11:45:28+1000 [ConnHandler] [INFO] connection with 84.114.30.55:28467 terminated
2015-11-18 11:45:28+1000 [ConnHandler] [INFO] connection with 97.84.133.102:1028 terminated
2015-11-18 11:45:28+1000 [ConnHandler] [INFO] connection with 72.66.113.63:28467 terminated
2015-11-18 11:45:28+1000 [ConnHandler] [INFO] connection with 173.79.161.229:45545 terminated
2015-11-18 11:45:28+1000 [ConnHandler] [INFO] connection with 97.84.133.102:1029 terminated
2015-11-18 11:45:28+1000 [ConnHandler] [INFO] connection with 128.199.32.197:28467 terminated
2015-11-18 11:45:28+1000 [ConnHandler] [INFO] connection with 205.186.154.163:28467 terminated
2015-11-18 11:45:28+1000 [ConnHandler] [INFO] connection with 128.199.118.253:28467 terminated
2015-11-18 11:45:28+1000 [ConnHandler] [INFO] connection with 71.91.198.104:28467 terminated
2015-11-18 11:45:28+1000 [ConnHandler] [INFO] connection with 98.223.170.66:28467 terminated

D:\Dropbox\01 OB1 and OpenBazaar\Projects\OB Server\OpenBazaar-Server>python openbazaard.py start -t
________             [94m         __________[0m
\_____  \ ______   ____   ____[94m\______   \_____  _____________  _____ _______[0m
 /   |   \\____ \_/ __ \ /    \[94m|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ [0m
/    |    \  |_> >  ___/|   |  \    [94m|   \ / __ \_/    /  / __ \_/ __ \|  | \/[0m
\_______  /   __/ \___  >___|  /[94m______  /(____  /_____ \(____  (____  /__|[0m
        \/|__|        \/     \/  [94m     \/      \/      \/     \/     \/[0m

OpenBazaar Server v0.1 starting...
2015-11-18 11:45:50+1000 [OpenBazaard] [INFO] Finding NAT Type...
2015-11-18 11:46:41+1000 [OpenBazaard] [INFO] Blocked on None:None
Traceback (most recent call last):
  File "openbazaard.py", line 271, in <module>
    Parser(OpenBazaard('/tmp/openbazaard.pid'))
  File "openbazaard.py", line 206, in __init__
    getattr(self, args.command)()
  File "openbazaard.py", line 248, in start
    run(args.testnet, args.loglevel, port, args.restallowip, args.wsallowip, args.ssl)
  File "openbazaard.py", line 106, in run
    reactor.listenUDP(port, protocol)
  File "C:\Python27\lib\site-packages\twisted\internet\posixbase.py", line 374, in listenUDP
    p.startListening()
  File "C:\Python27\lib\site-packages\twisted\internet\udp.py", line 175, in startListening
    self._bindSocket()
  File "C:\Python27\lib\site-packages\twisted\internet\udp.py", line 193, in _bindSocket
    skt.bind((self.interface, self.port))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: an integer is required

D:\Dropbox\01 OB1 and OpenBazaar\Projects\OB Server\OpenBazaar-Server>python openbazaard.py start -t -p 12234
________             [94m         __________[0m
\_____  \ ______   ____   ____[94m\______   \_____  _____________  _____ _______[0m
 /   |   \\____ \_/ __ \ /    \[94m|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ [0m
/    |    \  |_> >  ___/|   |  \    [94m|   \ / __ \_/    /  / __ \_/ __ \|  | \/[0m
\_______  /   __/ \___  >___|  /[94m______  /(____  /_____ \(____  (____  /__|[0m
        \/|__|        \/     \/  [94m     \/      \/      \/     \/     \/[0m

OpenBazaar Server v0.1 starting...
2015-11-18 11:46:55+1000 [OpenBazaard] [INFO] Finding NAT Type...
2015-11-18 11:47:05+1000 [OpenBazaard] [INFO] Restric NAT on 58.7.204.168:12234
2015-11-18 11:47:06+1000 [Server] [INFO] bootstrapping with 11 addresses, finding neighbors...
2015-11-18 11:47:06+1000 [OpenBazaard] [INFO] Libbitcoin server online
2015-11-18 11:47:07+1000 [ConnHandler] [INFO] connected to 104.131.6.245:28467
2015-11-18 11:47:07+1000 [ConnHandler] [INFO] connected to 205.186.154.163:28467
2015-11-18 11:47:07+1000 [ConnHandler] [INFO] connected to 128.199.32.197:28467
2015-11-18 11:47:07+1000 [ConnHandler] [INFO] connected to 128.199.118.253:28467
2015-11-18 11:47:08+1000 [ConnHandler] [INFO] connected to 84.114.30.55:28467
2015-11-18 11:47:08+1000 [ConnHandler] [INFO] connected to 173.79.161.229:45545
2015-11-18 11:47:10+1000 [ConnHandler] [INFO] connected to 97.84.133.102:1028
2015-11-18 11:47:10+1000 [ConnHandler] [INFO] connected to 72.66.113.63:28467
2015-11-18 11:47:10+1000 [ConnHandler] [INFO] connected to 71.91.198.104:28467
2015-11-18 11:47:11+1000 [ConnHandler] [INFO] connected to 97.84.133.102:1029
2015-11-18 11:47:14+1000 [Server] [INFO] fetching store listings from 128.199.32.197:28467
2015-11-18 11:47:14+1000 [Server] [INFO] fetching store listings from 97.84.133.102:1029
2015-11-18 11:47:14+1000 [Server] [INFO] fetching store listings from 128.199.118.253:28467
2015-11-18 11:47:14+1000 [Server] [INFO] fetching store listings from 205.186.154.163:28467
2015-11-18 11:47:14+1000 [Server] [INFO] fetching store listings from 97.84.133.102:1028
2015-11-18 11:47:14+1000 [Server] [INFO] fetching store listings from 173.79.161.229:45545
2015-11-18 11:47:14+1000 [Server] [INFO] fetching store listings from 98.223.170.66:28467
2015-11-18 11:47:14+1000 [Server] [INFO] fetching store listings from 72.66.113.63:28467
2015-11-18 11:47:14+1000 [Server] [INFO] fetching store listings from 71.91.198.104:28467
2015-11-18 11:47:14+1000 [Server] [INFO] fetching user metadata from 128.199.32.197:28467
2015-11-18 11:47:14+1000 [Server] [INFO] fetching user metadata from 205.186.154.163:28467
2015-11-18 11:47:14+1000 [Server] [INFO] fetching user metadata from 71.91.198.104:28467
2015-11-18 11:47:14+1000 [Server] [INFO] fetching user metadata from 72.66.113.63:28467
2015-11-18 11:47:14+1000 [Server] [INFO] fetching user metadata from 128.199.118.253:28467
2015-11-18 11:47:14+1000 [Server] [INFO] fetching user metadata from 97.84.133.102:1028
2015-11-18 11:47:14+1000 [Server] [INFO] fetching user metadata from 98.223.170.66:28467
2015-11-18 11:47:14+1000 [Server] [INFO] fetching user metadata from 97.84.133.102:1029
2015-11-18 11:47:14+1000 [Server] [INFO] fetching user metadata from 173.79.161.229:45545
2015-11-18 11:47:18+1000 [Server] [INFO] fetching profile from 128.199.118.253:28467
2015-11-18 11:47:19+1000 [Server] [INFO] fetching store listings from 128.199.118.253:28467
2015-11-18 11:47:19+1000 [Server] [INFO] fetching followers from 128.199.118.253:28467
2015-11-18 11:47:19+1000 [Server] [INFO] fetching following list from 128.199.118.253:28467
2015-11-18 11:47:26+1000 [Server] [INFO] fetching store listings from 128.199.118.253:28467
2015-11-18 11:47:27+1000 [Server] [INFO] fetching store listings from 128.199.118.253:28467
2015-11-18 11:47:28+1000 [Server] [INFO] fetching store listings from 128.199.118.253:28467
2015-11-18 11:47:29+1000 [ConnHandler] [INFO] connected to 97.84.133.102:28467
2015-11-18 11:47:29+1000 [Server] [INFO] fetching store listings from 128.199.118.253:28467
2015-11-18 11:48:35+1000 [OpenBazaard] [INFO] bootstrap complete, downloading outstanding messages...
2015-11-18 11:49:51+1000 [ConnHandler] [INFO] connection with 104.131.6.245:28467 terminated
2015-11-18 11:49:51+1000 [ConnHandler] [INFO] connection with 84.114.30.55:28467 terminated
2015-11-18 11:49:51+1000 [ConnHandler] [INFO] connection with 97.84.133.102:1028 terminated
2015-11-18 11:49:51+1000 [ConnHandler] [INFO] connection with 72.66.113.63:28467 terminated
2015-11-18 11:49:51+1000 [ConnHandler] [INFO] connection with 173.79.161.229:45545 terminated
2015-11-18 11:49:51+1000 [ConnHandler] [INFO] connection with 97.84.133.102:1029 terminated
2015-11-18 11:49:51+1000 [ConnHandler] [INFO] connection with 128.199.32.197:28467 terminated
2015-11-18 11:49:51+1000 [ConnHandler] [INFO] connection with 205.186.154.163:28467 terminated
2015-11-18 11:49:51+1000 [ConnHandler] [INFO] connection with 128.199.118.253:28467 terminated
2015-11-18 11:49:51+1000 [ConnHandler] [INFO] connection with 71.91.198.104:28467 terminated
2015-11-18 11:49:51+1000 [ConnHandler] [INFO] connection with 97.84.133.102:28467 terminated

D:\Dropbox\01 OB1 and OpenBazaar\Projects\OB Server\OpenBazaar-Server>python openbazaard.py start -t
________             [94m         __________[0m
\_____  \ ______   ____   ____[94m\______   \_____  _____________  _____ _______[0m
 /   |   \\____ \_/ __ \ /    \[94m|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ [0m
/    |    \  |_> >  ___/|   |  \    [94m|   \ / __ \_/    /  / __ \_/ __ \|  | \/[0m
\_______  /   __/ \___  >___|  /[94m______  /(____  /_____ \(____  (____  /__|[0m
        \/|__|        \/     \/  [94m     \/      \/      \/     \/     \/[0m

OpenBazaar Server v0.1 starting...
2015-11-18 11:49:58+1000 [OpenBazaard] [INFO] Finding NAT Type...
2015-11-18 11:50:07+1000 [OpenBazaard] [INFO] Restric NAT on 58.7.204.168:28467
2015-11-18 11:50:08+1000 [OpenBazaard] [INFO] Libbitcoin server online
2015-11-18 11:50:08+1000 [Server] [INFO] bootstrapping with 19 addresses, finding neighbors...
2015-11-18 11:50:09+1000 [ConnHandler] [INFO] connected to 104.131.6.245:28467
2015-11-18 11:50:09+1000 [ConnHandler] [INFO] connected to 205.186.154.163:28467
2015-11-18 11:50:09+1000 [ConnHandler] [INFO] connected to 128.199.118.253:28467
2015-11-18 11:50:09+1000 [ConnHandler] [INFO] connected to 173.79.161.229:45545
2015-11-18 11:50:09+1000 [ConnHandler] [INFO] connected to 84.114.30.55:28467
2015-11-18 11:50:09+1000 [ConnHandler] [INFO] connected to 128.199.32.197:28467
2015-11-18 11:50:12+1000 [ConnHandler] [INFO] connected to 72.66.113.63:28467
2015-11-18 11:50:12+1000 [ConnHandler] [INFO] connected to 97.84.133.102:1029
2015-11-18 11:50:12+1000 [ConnHandler] [INFO] connected to 71.91.198.104:28467
2015-11-18 11:50:13+1000 [ConnHandler] [INFO] connected to 97.84.133.102:1028
2015-11-18 11:50:15+1000 [ConnHandler] [INFO] connection with 104.131.6.245:28467 terminated
2015-11-18 11:50:15+1000 [ConnHandler] [INFO] connection with 84.114.30.55:28467 terminated
2015-11-18 11:50:15+1000 [ConnHandler] [INFO] connection with 97.84.133.102:1028 terminated
2015-11-18 11:50:15+1000 [ConnHandler] [INFO] connection with 173.79.161.229:45545 terminated
2015-11-18 11:50:15+1000 [ConnHandler] [INFO] connection with 97.84.133.102:1029 terminated
2015-11-18 11:50:15+1000 [ConnHandler] [INFO] connection with 128.199.32.197:28467 terminated
2015-11-18 11:50:15+1000 [ConnHandler] [INFO] connection with 205.186.154.163:28467 terminated
2015-11-18 11:50:15+1000 [ConnHandler] [INFO] connection with 128.199.118.253:28467 terminated
2015-11-18 11:50:15+1000 [ConnHandler] [INFO] connection with 71.91.198.104:28467 terminated
2015-11-18 11:50:15+1000 [ConnHandler] [INFO] connection with 72.66.113.63:28467 terminated

D:\Dropbox\01 OB1 and OpenBazaar\Projects\OB Server\OpenBazaar-Server>python openbazaard.py start -t
________             [94m         __________[0m
\_____  \ ______   ____   ____[94m\______   \_____  _____________  _____ _______[0m
 /   |   \\____ \_/ __ \ /    \[94m|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ [0m
/    |    \  |_> >  ___/|   |  \    [94m|   \ / __ \_/    /  / __ \_/ __ \|  | \/[0m
\_______  /   __/ \___  >___|  /[94m______  /(____  /_____ \(____  (____  /__|[0m
        \/|__|        \/     \/  [94m     \/      \/      \/     \/     \/[0m

OpenBazaar Server v0.1 starting...
2015-11-18 11:50:23+1000 [OpenBazaard] [INFO] Finding NAT Type...
2015-11-18 11:50:24+1000 [OpenBazaard] [INFO] Full Cone on 58.7.204.168:28467
2015-11-18 11:50:25+1000 [OpenBazaard] [INFO] Libbitcoin server online
2015-11-18 11:50:25+1000 [Server] [INFO] bootstrapping with 19 addresses, finding neighbors...
2015-11-18 11:50:26+1000 [ConnHandler] [INFO] connected to 104.131.6.245:28467
2015-11-18 11:50:26+1000 [ConnHandler] [INFO] connected to 205.186.154.163:28467
2015-11-18 11:50:26+1000 [ConnHandler] [INFO] connected to 97.84.133.102:1028
2015-11-18 11:50:26+1000 [ConnHandler] [INFO] connected to 128.199.118.253:28467
2015-11-18 11:50:26+1000 [ConnHandler] [INFO] connected to 72.66.113.63:28467
2015-11-18 11:50:26+1000 [ConnHandler] [INFO] connected to 97.84.133.102:1029
2015-11-18 11:50:26+1000 [ConnHandler] [INFO] connected to 173.79.161.229:45545
2015-11-18 11:50:26+1000 [ConnHandler] [INFO] connected to 71.91.198.104:28467
2015-11-18 11:50:26+1000 [ConnHandler] [INFO] connected to 84.114.30.55:28467
2015-11-18 11:50:26+1000 [ConnHandler] [INFO] connected to 128.199.32.197:28467
2015-11-18 11:50:29+1000 [ConnHandler] [INFO] connection with 104.131.6.245:28467 terminated
2015-11-18 11:50:29+1000 [ConnHandler] [INFO] connection with 84.114.30.55:28467 terminated
2015-11-18 11:50:29+1000 [ConnHandler] [INFO] connection with 97.84.133.102:1028 terminated
2015-11-18 11:50:29+1000 [ConnHandler] [INFO] connection with 173.79.161.229:45545 terminated
2015-11-18 11:50:29+1000 [ConnHandler] [INFO] connection with 97.84.133.102:1029 terminated
2015-11-18 11:50:29+1000 [ConnHandler] [INFO] connection with 128.199.32.197:28467 terminated
2015-11-18 11:50:29+1000 [ConnHandler] [INFO] connection with 205.186.154.163:28467 terminated
2015-11-18 11:50:29+1000 [ConnHandler] [INFO] connection with 128.199.118.253:28467 terminated
2015-11-18 11:50:29+1000 [ConnHandler] [INFO] connection with 71.91.198.104:28467 terminated
2015-11-18 11:50:29+1000 [ConnHandler] [INFO] connection with 72.66.113.63:28467 terminated

D:\Dropbox\01 OB1 and OpenBazaar\Projects\OB Server\OpenBazaar-Server>python openbazaard.py start -t
________             [94m         __________[0m
\_____  \ ______   ____   ____[94m\______   \_____  _____________  _____ _______[0m
 /   |   \\____ \_/ __ \ /    \[94m|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ [0m
/    |    \  |_> >  ___/|   |  \    [94m|   \ / __ \_/    /  / __ \_/ __ \|  | \/[0m
\_______  /   __/ \___  >___|  /[94m______  /(____  /_____ \(____  (____  /__|[0m
        \/|__|        \/     \/  [94m     \/      \/      \/     \/     \/[0m

OpenBazaar Server v0.1 starting...
2015-11-18 11:50:33+1000 [OpenBazaard] [INFO] Finding NAT Type...
2015-11-18 11:50:33+1000 [OpenBazaard] [INFO] Full Cone on 58.7.204.168:28467
2015-11-18 11:50:34+1000 [OpenBazaard] [INFO] Libbitcoin server online
2015-11-18 11:50:34+1000 [Server] [INFO] bootstrapping with 19 addresses, finding neighbors...
2015-11-18 11:50:35+1000 [ConnHandler] [INFO] connected to 104.131.6.245:28467
2015-11-18 11:50:35+1000 [ConnHandler] [INFO] connected to 205.186.154.163:28467
2015-11-18 11:50:35+1000 [ConnHandler] [INFO] connected to 72.66.113.63:28467
2015-11-18 11:50:35+1000 [ConnHandler] [INFO] connected to 128.199.118.253:28467
2015-11-18 11:50:35+1000 [ConnHandler] [INFO] connected to 71.91.198.104:28467
2015-11-18 11:50:35+1000 [ConnHandler] [INFO] connected to 84.114.30.55:28467
2015-11-18 11:50:35+1000 [ConnHandler] [INFO] connected to 97.84.133.102:1029
2015-11-18 11:50:35+1000 [ConnHandler] [INFO] connected to 173.79.161.229:45545
2015-11-18 11:50:35+1000 [ConnHandler] [INFO] connected to 128.199.32.197:28467
2015-11-18 11:50:36+1000 [ConnHandler] [INFO] connected to 97.84.133.102:1028
2015-11-18 11:50:39+1000 [ConnHandler] [INFO] connection with 104.131.6.245:28467 terminated
2015-11-18 11:50:39+1000 [ConnHandler] [INFO] connection with 84.114.30.55:28467 terminated
2015-11-18 11:50:39+1000 [ConnHandler] [INFO] connection with 97.84.133.102:1028 terminated
2015-11-18 11:50:39+1000 [ConnHandler] [INFO] connection with 173.79.161.229:45545 terminated
2015-11-18 11:50:39+1000 [ConnHandler] [INFO] connection with 97.84.133.102:1029 terminated
2015-11-18 11:50:39+1000 [ConnHandler] [INFO] connection with 128.199.32.197:28467 terminated
2015-11-18 11:50:39+1000 [ConnHandler] [INFO] connection with 205.186.154.163:28467 terminated
2015-11-18 11:50:39+1000 [ConnHandler] [INFO] connection with 128.199.118.253:28467 terminated
2015-11-18 11:50:39+1000 [ConnHandler] [INFO] connection with 71.91.198.104:28467 terminated
2015-11-18 11:50:39+1000 [ConnHandler] [INFO] connection with 72.66.113.63:28467 terminated

D:\Dropbox\01 OB1 and OpenBazaar\Projects\OB Server\OpenBazaar-Server>python openbazaard.py start -t
________             [94m         __________[0m
\_____  \ ______   ____   ____[94m\______   \_____  _____________  _____ _______[0m
 /   |   \\____ \_/ __ \ /    \[94m|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ [0m
/    |    \  |_> >  ___/|   |  \    [94m|   \ / __ \_/    /  / __ \_/ __ \|  | \/[0m
\_______  /   __/ \___  >___|  /[94m______  /(____  /_____ \(____  (____  /__|[0m
        \/|__|        \/     \/  [94m     \/      \/      \/     \/     \/[0m

OpenBazaar Server v0.1 starting...
2015-11-18 11:51:14+1000 [OpenBazaard] [INFO] Finding NAT Type...
2015-11-18 11:51:14+1000 [OpenBazaard] [INFO] Full Cone on 58.7.204.168:28467
2015-11-18 11:51:15+1000 [OpenBazaard] [INFO] Libbitcoin server online
2015-11-18 11:51:15+1000 [Server] [INFO] bootstrapping with 19 addresses, finding neighbors...
2015-11-18 11:51:16+1000 [ConnHandler] [INFO] connected to 104.131.6.245:28467
2015-11-18 11:51:16+1000 [ConnHandler] [INFO] connected to 97.84.133.102:1028
2015-11-18 11:51:16+1000 [ConnHandler] [INFO] connected to 205.186.154.163:28467
2015-11-18 11:51:16+1000 [ConnHandler] [INFO] connected to 72.66.113.63:28467
2015-11-18 11:51:16+1000 [ConnHandler] [INFO] connected to 128.199.118.253:28467
2015-11-18 11:51:16+1000 [ConnHandler] [INFO] connected to 97.84.133.102:1029
2015-11-18 11:51:16+1000 [ConnHandler] [INFO] connected to 173.79.161.229:45545
2015-11-18 11:51:16+1000 [ConnHandler] [INFO] connected to 71.91.198.104:28467
2015-11-18 11:51:16+1000 [ConnHandler] [INFO] connected to 84.114.30.55:28467
2015-11-18 11:51:16+1000 [ConnHandler] [INFO] connected to 128.199.32.197:28467
2015-11-18 11:51:27+1000 [ConnHandler] [INFO] connection with 104.131.6.245:28467 terminated
2015-11-18 11:51:27+1000 [ConnHandler] [INFO] connection with 84.114.30.55:28467 terminated
2015-11-18 11:51:27+1000 [ConnHandler] [INFO] connection with 97.84.133.102:1028 terminated
2015-11-18 11:51:27+1000 [ConnHandler] [INFO] connection with 173.79.161.229:45545 terminated
2015-11-18 11:51:27+1000 [ConnHandler] [INFO] connection with 97.84.133.102:1029 terminated
2015-11-18 11:51:27+1000 [ConnHandler] [INFO] connection with 128.199.32.197:28467 terminated
2015-11-18 11:51:27+1000 [ConnHandler] [INFO] connection with 205.186.154.163:28467 terminated
2015-11-18 11:51:27+1000 [ConnHandler] [INFO] connection with 128.199.118.253:28467 terminated
2015-11-18 11:51:27+1000 [ConnHandler] [INFO] connection with 71.91.198.104:28467 terminated
2015-11-18 11:51:27+1000 [ConnHandler] [INFO] connection with 72.66.113.63:28467 terminated

D:\Dropbox\01 OB1 and OpenBazaar\Projects\OB Server\OpenBazaar-Server>python openbazaard.py start -t
________             [94m         __________[0m
\_____  \ ______   ____   ____[94m\______   \_____  _____________  _____ _______[0m
 /   |   \\____ \_/ __ \ /    \[94m|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ [0m
/    |    \  |_> >  ___/|   |  \    [94m|   \ / __ \_/    /  / __ \_/ __ \|  | \/[0m
\_______  /   __/ \___  >___|  /[94m______  /(____  /_____ \(____  (____  /__|[0m
        \/|__|        \/     \/  [94m     \/      \/      \/     \/     \/[0m

OpenBazaar Server v0.1 starting...
2015-11-18 11:51:31+1000 [OpenBazaard] [INFO] Finding NAT Type...
2015-11-18 11:51:32+1000 [OpenBazaard] [INFO] Full Cone on 58.7.204.168:28467
2015-11-18 11:51:33+1000 [OpenBazaard] [INFO] Libbitcoin server online
2015-11-18 11:51:33+1000 [Server] [INFO] bootstrapping with 9 addresses, finding neighbors...
2015-11-18 11:51:34+1000 [ConnHandler] [INFO] connected to 104.131.6.245:28467
2015-11-18 11:51:34+1000 [ConnHandler] [INFO] connected to 97.84.133.102:1029
2015-11-18 11:51:34+1000 [ConnHandler] [INFO] connected to 72.66.113.63:28467
2015-11-18 11:51:34+1000 [ConnHandler] [INFO] connected to 71.91.198.104:28467
2015-11-18 11:51:34+1000 [ConnHandler] [INFO] connected to 84.114.30.55:28467
2015-11-18 11:51:34+1000 [ConnHandler] [INFO] connected to 173.79.161.229:45545
2015-11-18 11:51:34+1000 [ConnHandler] [INFO] connected to 128.199.32.197:28467
2015-11-18 11:51:34+1000 [ConnHandler] [INFO] connected to 128.199.118.253:28467
2015-11-18 11:51:37+1000 [ConnHandler] [INFO] connected to 205.186.154.163:28467
2015-11-18 11:51:37+1000 [ConnHandler] [INFO] connected to 97.84.133.102:1028
2015-11-18 11:51:40+1000 [ConnHandler] [INFO] connection with 104.131.6.245:28467 terminated
2015-11-18 11:51:40+1000 [ConnHandler] [INFO] connection with 84.114.30.55:28467 terminated
2015-11-18 11:51:40+1000 [ConnHandler] [INFO] connection with 97.84.133.102:1028 terminated
2015-11-18 11:51:40+1000 [ConnHandler] [INFO] connection with 72.66.113.63:28467 terminated
2015-11-18 11:51:40+1000 [ConnHandler] [INFO] connection with 173.79.161.229:45545 terminated
2015-11-18 11:51:40+1000 [ConnHandler] [INFO] connection with 97.84.133.102:1029 terminated
2015-11-18 11:51:40+1000 [ConnHandler] [INFO] connection with 128.199.32.197:28467 terminated
2015-11-18 11:51:40+1000 [ConnHandler] [INFO] connection with 205.186.154.163:28467 terminated
2015-11-18 11:51:40+1000 [ConnHandler] [INFO] connection with 128.199.118.253:28467 terminated
2015-11-18 11:51:40+1000 [ConnHandler] [INFO] connection with 71.91.198.104:28467 terminated

D:\Dropbox\01 OB1 and OpenBazaar\Projects\OB Server\OpenBazaar-Server>python openbazaard.py start -t
________             [94m         __________[0m
\_____  \ ______   ____   ____[94m\______   \_____  _____________  _____ _______[0m
 /   |   \\____ \_/ __ \ /    \[94m|    |  _/\__  \ \___   /\__  \ \__  \\_  __ \ [0m
/    |    \  |_> >  ___/|   |  \    [94m|   \ / __ \_/    /  / __ \_/ __ \|  | \/[0m
\_______  /   __/ \___  >___|  /[94m______  /(____  /_____ \(____  (____  /__|[0m
        \/|__|        \/     \/  [94m     \/      \/      \/     \/     \/[0m

OpenBazaar Server v0.1 starting...
2015-11-18 11:52:43+1000 [OpenBazaard] [INFO] Finding NAT Type...
2015-11-18 11:52:43+1000 [OpenBazaard] [INFO] Full Cone on 58.7.204.168:28467
2015-11-18 11:52:44+1000 [OpenBazaard] [INFO] Libbitcoin server online
2015-11-18 11:52:44+1000 [Server] [INFO] bootstrapping with 9 addresses, finding neighbors...
2015-11-18 11:52:45+1000 [ConnHandler] [INFO] connected to 104.131.6.245:28467
2015-11-18 11:52:45+1000 [ConnHandler] [INFO] connected to 97.84.133.102:1028
2015-11-18 11:52:45+1000 [ConnHandler] [INFO] connected to 71.91.198.104:28467
2015-11-18 11:52:45+1000 [ConnHandler] [INFO] connected to 84.114.30.55:28467
2015-11-18 11:52:45+1000 [ConnHandler] [INFO] connected to 173.79.161.229:45545
2015-11-18 11:52:45+1000 [ConnHandler] [INFO] connected to 128.199.32.197:28467
2015-11-18 11:52:45+1000 [ConnHandler] [INFO] connected to 128.199.118.253:28467
2015-11-18 11:52:48+1000 [ConnHandler] [INFO] connected to 205.186.154.163:28467
2015-11-18 11:52:49+1000 [ConnHandler] [INFO] connected to 72.66.113.63:28467
2015-11-18 11:52:49+1000 [ConnHandler] [INFO] connected to 97.84.133.102:1029
```

**Comment by cpacia** [comment]
It will say full cone if the stun bind is still in place from the last time.

**Comment by cpacia** [comment]
Looks like bug went away. We can reopen if it comes up again.
