### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Server#95]
I'm getting the same unhandled error several times. Below is my full console log:

```
OpenBazaar Server v0.1 starting...
Generating GUID, this may take a few minutes...
2015-12-12 16:17:50+0000 [OpenBazaard] [INFO] Finding NAT Type...
2015-12-12 16:17:50+0000 [OpenBazaard] [INFO] Full Cone on 146.199.254.106:18467
2015-12-12 16:17:50+0000 [Server] [INFO] querying seed.openbazaar.org:8080 for peers
2015-12-12 16:17:50+0000 [Server] [INFO] seed.openbazaar.org:8080 returned 15 addresses
2015-12-12 16:17:51+0000 [Server] [INFO] bootstrapping with 15 addresses, finding neighbors...
2015-12-12 16:17:53+0000 [-] [INFO] Libbitcoin server online
2015-12-12 16:18:06+0000 [api.ws.WSFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 73, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	  File "/usr/local/lib/python2.7/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 1062, in doRead
	    protocol = self.factory.buildProtocol(self._buildAddr(addr))
	  File "/usr/local/lib/python2.7/site-packages/twisted/internet/protocol.py", line 123, in buildProtocol
	    p = self.protocol()
	  File "/usr/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 665, in __init__
	    self.is_closed = txaio.create_future()
	  File "/usr/local/lib/python2.7/site-packages/txaio/_unframework.py", line 43, in _throw_usage_error
	    "To use txaio, you must first select a framework "
	exceptions.RuntimeError: To use txaio, you must first select a framework with .use_twisted() or .use_txaio()

Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 1062, in doRead
    protocol = self.factory.buildProtocol(self._buildAddr(addr))
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/protocol.py", line 123, in buildProtocol
    p = self.protocol()
  File "/usr/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 665, in __init__
    self.is_closed = txaio.create_future()
  File "/usr/local/lib/python2.7/site-packages/txaio/_unframework.py", line 43, in _throw_usage_error
    "To use txaio, you must first select a framework "
exceptions.RuntimeError: To use txaio, you must first select a framework with .use_twisted() or .use_txaio()
2015-12-12 16:18:11+0000 [OpenBazaard] [INFO] bootstrap complete
2015-12-12 16:21:33+0000 [api.ws.WSFactory] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 73, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	  File "/usr/local/lib/python2.7/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 1062, in doRead
	    protocol = self.factory.buildProtocol(self._buildAddr(addr))
	  File "/usr/local/lib/python2.7/site-packages/twisted/internet/protocol.py", line 123, in buildProtocol
	    p = self.protocol()
	  File "/usr/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 665, in __init__
	    self.is_closed = txaio.create_future()
	  File "/usr/local/lib/python2.7/site-packages/txaio/_unframework.py", line 43, in _throw_usage_error
	    "To use txaio, you must first select a framework "
	exceptions.RuntimeError: To use txaio, you must first select a framework with .use_twisted() or .use_txaio()

Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/twisted/python/log.py", line 73, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 1062, in doRead
    protocol = self.factory.buildProtocol(self._buildAddr(addr))
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/protocol.py", line 123, in buildProtocol
    p = self.protocol()
  File "/usr/local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 665, in __init__
    self.is_closed = txaio.create_future()
  File "/usr/local/lib/python2.7/site-packages/txaio/_unframework.py", line 43, in _throw_usage_error
    "To use txaio, you must first select a framework "
exceptions.RuntimeError: To use txaio, you must first select a framework with .use_twisted() or .use_txaio()
```

**Comment by cpacia** [comment]
The server requires txaio==1.1.0. We put that in the requirements.
